### ISSUE TITLE
Missing initialization in remotetrx

### ISSUE THREAD

**Issue by pe1chl** [sm0svx/svxlink#101]
When starting remotetrx on Debian Wheezy, the following message appears:

remotetrx: Libgcrypt warning: missing initialization - please fix the application

Probably a warning added in a recent update.  It does not occur when starting svxlink.

**Comment by pe1chl** [comment]
This problem was fixed but it has returned in the current master (Apr 3 2015).
Apr  4 10:25:03 hvs remotetrx: Libgcrypt warning: missing initialization - please fix the application

**Comment by sm0svx** [comment]
Reopening issue since the problem has reappeared.

**Comment by sm0svx** [comment]
Now it should be fixed!
