### ISSUE TITLE
Lock-up into permanent transmit - Evidence points to MetarInformation

### ISSUE THREAD

**Issue by f5vmr** [sm0svx/svxlink#117]
For three mornings (out of 5 so far) I have found our repeater in permanent transmit with no access possible. However I was able to access the rPI software at distance and facilitate a reboot which was uneventful, and the repeater returned to normal service.

In reading the log for the ocurrences creating the stuck transmission, I found that a night-owl has been accessing the MetarInformation module, and had issued a "#" either 2 or three times, after each occasion the log ceases as the time it happened. If nothing else it has given the amplifier on our repeater a good soak test. What I cannot determine is the actual length of the tone this person used. DTMF muting is set ON.

So for the moment I have excluded ModuleMetarInformation from the running schedule until we resolve this issue.

The raspberry is using GPIO for COS and PTT and those signals are being passed to an ARS Echolink interface module, so everything is properly isolated. The whole unit has been running in my workshop four 4 weeks on a UHF repeater into a dummy load, and has not experienced this problem before.

However i noticed that in a couple of instances, not associated with the problem in the header that an error report had been generated "pthread_mutex_destroy:error 16" & "error 10". Whether this has an impact on the transmit problem or not I cannot imagine.

**Comment by f5vmr** [comment]
Model B+ has had no issues since becoming operational on the Vhf repeater. Unless anyone still has a model B then I think can close this issue.

**Comment by sm0svx** [comment]
Ok, good. If someone have the same issue they can reopen the issue but it seems the problem is hardware related rather than software related, so the solution is to buy a B+. Thanks for reporting back!
