### ISSUE TITLE
Feature request: freeradionetwork module

### ISSUE THREAD

**Issue by sh123** [sm0svx/svxlink#120]
Hi,

I'm using svxlink for more than a year on linux ARM7 device and I'm really happy about it. What I'm really missing is support for freeradionetwork (http://freeradionetwork.eu/ = EchoLink for non-hams). Project is very interesting (especially to attract more non-hams, who can get a license in the future, plus there are many nodes crosslinking CB, PMR and LPD channels in different countries and channels are accessible from PC similar to EchoLink, also some people are running crosslink to Zello), but they do not have proper support for linux systems. There is linfrn project (http://linfrn.webs.com/), but it is not very active. Also having one service which you can configure for different needs using modules is much more convinient especially on non-pc platforms.

It would be really cool if there will be svxlink module which will allow running FRN gateway. Their protocol seems to be somewhat documented http://freeradionetwork.eu/frnprotocol.htm

If there is interest from svxlink community, but lack of resources I can contribute to this module.

Cheers.

**Comment by sh123** [comment]
Almost completed, was running and using FRN module actively during last week on PC fixing some minor issues at the same time. Today built it for ARM and testing with my RIG on ARM board.

**Comment by sh123** [comment]
There is a client downloadable at freeradionetwork.eu, it is possible to use any server, each server has room called Test with the parrot. I will review code once more and create pull request. I was using it with my RIG during this week, there are still might be some unexpected issues or stability problems, but for alpha version it seems to be ok.

**Comment by sm0svx** [comment]
Associated pull request: #126.

**Comment by sm0svx** [comment]
The #126 pull request implement this
