### ISSUE TITLE
runasuser does not affect search path for svxlink.conf

### ISSUE THREAD

**Issue by granitepenguin** [sm0svx/svxlink#138]
Per discussion in the mailing list:

I'm starting svxlink as root and changing to the svxlink user using a command like this:
```
svxlink --daemon --logfile=/var/log/svxlink.log --runasuser=svxlink
```
What I'm seeing in the log is the following:
```
Tue Apr 21 12:26:48 2015: fopen: Permission denied
```                                                                                                                      
If I trace it, I find that it's looking for svxlink.conf in root's home directory, presumably after it's already switched to the svxlink user:
```
open("/root/.svxlink/svxlink.conf", O_RDONLY) = -1 EACCES (Permission denied)
fopen: Permission denied
close(3)                                = 0
```
So it would seem logical that the .svxlink path that the system checks should be based on the runasuser, not the user that started svxlink (unless no runasuser is supplied, obviously).  It would also be nice if the error message was more verbose (ie, instead of just displaying fopen: Permission denied, it should print what file it's not allowed to open).                                                               

A workaround is to explicitly state the config file location:
```
svxlink --daemon --logfile=/var/log/svxlink --config=/etc/svxlink/svxlink.conf --runasuser=svxlink
```
But I would offer that it's a reasonable assumption that the --runasuser option would dictate where to check for home directory config files, since it implies expected (desired?) differences in permissions.

**Comment by sm0svx** [comment]
If the --runasuser switch is used in SvxLink and RemoteTrx, the home directory set up for the target user is used rather than using the HOME environment variable for the user starting the process.

Cleaned up error printouts.
