### ISSUE TITLE
contrib directory

### ISSUE THREAD

**Issue by dl1hrc** [sm0svx/svxlink#146]
The SvxLink trunk should have a contrib or 3rd-party directory where information about userspecific developments relating to the SvxLink project can be stored. The directory should have at least a  README and INSTALL file with further information.

**Comment by sm3sgp** [comment]
Is the contrib directory implemented now?
[https://github.com/sm0svx/svxlink/pull/129#issuecomment-277529538](url)

**Comment by dl1hrc** [comment]
yes:
/svxlink/src/svxlink/contrib
