### ISSUE TITLE
disallow beep after PTT

### ISSUE THREAD

**Issue by oibafrc** [sm0svx/svxlink#151]
hello,
I'm using SVXLINK to make the link between 3 repeaters.
I'm not using echolink.
How to disable the beep that sounds when the end of each communication?

thanks,

Fábio

**Comment by pe1chl** [comment]
Please don't use the issue tracking system to ask user questions!  It is for reporting anomalies
and registering feature requests.

The beep sounds are made in Logic.tcl in the function send_rgr_sound.
Read https://github.com/sm0svx/svxlink/wiki/InstallationInstructions to see how you can modify
scripts like that for local use.
