### ISSUE TITLE
Mailings List

### ISSUE THREAD

**Issue by f5vmr** [sm0svx/svxlink#152]
Mailing lists section is offline. Definitely an issue :)

**Comment by sm0svx** [comment]
Seems like a big part of SourceForge is offline. They're working on it.
https://mobile.twitter.com/sfnet_ops

**Comment by f5vmr** [comment]
Thanks - watching this space.

**Comment by f5vmr** [comment]
Sourceforge is back but not the developer pages containing the mailing lists.

**Comment by sm0svx** [comment]
Everything seem to be good now. Closing issue.
