### ISSUE TITLE
make docs issues

### ISSUE THREAD

**Issue by RichNeese** [sm0svx/svxlink#169]
as of this am . I did a new test build with your current changes. this is the output from make docs.

Warning: Tag `SYMBOL_CACHE_SIZE' at line 310 of file`/usr/src/svxlink/src/build/doc/doxygen.echolib' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: Tag `SHOW_DIRECTORIES' at line 519 of file`/usr/src/svxlink/src/build/doc/doxygen.echolib' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: Tag `HTML_ALIGN_MEMBERS' at line 901 of file`/usr/src/svxlink/src/build/doc/doxygen.echolib' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: Tag `USE_INLINE_TREES' at line 1088 of file`/usr/src/svxlink/src/build/doc/doxygen.echolib' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: Tag `XML_SCHEMA' at line 1340 of file`/usr/src/svxlink/src/build/doc/doxygen.echolib' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: Tag `XML_DTD' at line 1346 of file`/usr/src/svxlink/src/build/doc/doxygen.echolib' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: doxygen no longer ships with the FreeSans font.
You may want to clear or change DOT_FONTNAME.
Otherwise you run the risk that the wrong font is being used for dot generated graphs.
Notice: Output directory `/usr/src/svxlink/src/build/doc/echolib' does not exist. I have created it for you.
Searching for include files...
Searching for example files...
Searching for files in directory /usr/src/svxlink/src/build/doc/echolib
Searching for images...
Searching for dot files...
Searching for msc files...
Searching for dia files...
Searching for files to exclude
Searching for files to process...
Searching for files in directory /usr/src/svxlink/src/build/include
Reading and parsing tag files
Parsing files
Preprocessing /usr/src/svxlink/src/build/include/EchoLinkDirectory.h...
Parsing file /usr/src/svxlink/src/build/include/EchoLinkDirectory.h...
Preprocessing /usr/src/svxlink/src/build/include/EchoLinkDispatcher.h...
Parsing file /usr/src/svxlink/src/build/include/EchoLinkDispatcher.h...
Preprocessing /usr/src/svxlink/src/build/include/EchoLinkProxy.h...
Parsing file /usr/src/svxlink/src/build/include/EchoLinkProxy.h...
Preprocessing /usr/src/svxlink/src/build/include/EchoLinkQso.h...
Parsing file /usr/src/svxlink/src/build/include/EchoLinkQso.h...
Preprocessing /usr/src/svxlink/src/build/include/EchoLinkStationData.h...
Parsing file /usr/src/svxlink/src/build/include/EchoLinkStationData.h...
Preprocessing /usr/src/svxlink/src/echolib/mainpage.dox...
Parsing file /usr/src/svxlink/src/echolib/mainpage.dox...
Building group list...
Building directory list...
Building namespace list...
Building file list...
Building class list...
Associating documentation with classes...
Computing nesting relations for classes...
Building example list...
Searching for enumerations...
Searching for documented typedefs...
Searching for members imported via using declarations...
Searching for included using directives...
Searching for documented variables...
Building interface member list...
Building member list...
Searching for friends...
Searching for documented defines...
Computing class inheritance relations...
Computing class usage relations...
Flushing cached template relations that have become invalid...
Creating members for template instances...
Computing class relations...
Add enum values to enums...
Searching for member function documentation...
Building page list...
Search for main page...
Computing page relations...
Determining the scope of groups...
Sorting lists...
Freeing entry tree
Determining which enums are documented
Computing member relations...
Building full member lists recursively...
Adding members to member groups.
Computing member references...
Inheriting documentation...
Generating disk names...
Adding source references...
Adding xrefitems...
Sorting member lists...
Computing dependencies between directories...
Generating citations page...
Counting data structures...
Resolving user defined references...
Finding anchors and sections in the documentation...
Transferring function references...
Combining using relations...
Adding members to index pages...
Generating style sheet...
Generating example documentation...
Generating docs for example EchoLinkDirectory_demo.cpp...
/usr/src/svxlink/src/build/include/EchoLinkDirectory.h:122: warning: included file EchoLinkDirectory_demo.cpp is not found. Check your EXAMPLE_PATH
Generating docs for example EchoLinkDispatcher_demo.cpp...
/usr/src/svxlink/src/build/include/EchoLinkDispatcher.h:123: warning: included file EchoLinkDispatcher_demo.cpp is not found. Check your EXAMPLE_PATH
Generating docs for example EchoLinkProxy_demo.cpp...
/usr/src/svxlink/src/build/include/EchoLinkProxy.h:29: warning: included file EchoLinkProxy_demo.cpp is not found. Check your EXAMPLE_PATH
Generating docs for example EchoLinkQso_demo.cpp...
/usr/src/svxlink/src/build/include/EchoLinkQso.h:135: warning: included file EchoLinkQso_demo.cpp is not found. Check your EXAMPLE_PATH
Generating file sources...
Generating code for file EchoLinkDirectory.h...
Generating code for file EchoLinkDispatcher.h...
Generating code for file EchoLinkProxy.h...
Generating code for file EchoLinkQso.h...
Generating code for file EchoLinkStationData.h...
Parsing code for file mainpage.dox...
Generating file documentation...
Generating docs for file EchoLinkDirectory.h...
Generating docs for file EchoLinkDispatcher.h...
Generating docs for file EchoLinkProxy.h...
Generating docs for file EchoLinkQso.h...
Generating docs for file EchoLinkStationData.h...
Generating docs for file mainpage.dox...
Generating page documentation...
Generating group documentation...
Generating class documentation...
Generating namespace index...
Generating docs for namespace EchoLink
Generating docs for compound EchoLink::Directory...
/usr/src/svxlink/src/build/include/EchoLinkDirectory.h:127: warning: included file EchoLinkDirectory_demo.cpp is not found. Check your EXAMPLE_PATH
Generating docs for compound EchoLink::Dispatcher...
/usr/src/svxlink/src/build/include/EchoLinkDispatcher.h:140: warning: included file EchoLinkDispatcher_demo.cpp is not found. Check your EXAMPLE_PATH
Generating docs for compound EchoLink::Proxy...
/usr/src/svxlink/src/build/include/EchoLinkProxy.h:125: warning: included file EchoLinkProxy_demo.cpp is not found. Check your EXAMPLE_PATH
Generating docs for compound EchoLink::Qso...
/usr/src/svxlink/src/build/include/EchoLinkQso.h:142: warning: included file EchoLinkQso_demo.cpp is not found. Check your EXAMPLE_PATH
Generating docs for nested compound EchoLink::Qso::RawPacket...
Generating docs for nested compound EchoLink::Qso::VoicePacket...
Generating docs for compound EchoLink::StationData...
Generating graph info page...
Generating directory documentation...
Generating index page...
Generating page index...
Generating module index...
Generating namespace index...
Generating namespace member index...
Generating annotated compound index...
Generating alphabetical compound index...
Generating hierarchical class index...
Generating member index...
Generating file index...
Generating file member index...
Generating example index...
finalizing index lists...
Generating SQLITE3 output...
Initializing DB schema...
Generating Sqlite3 output for class EchoLink::Qso::VoicePacket::@0
Generating Sqlite3 output for class @1
Generating Sqlite3 output for class Async::AudioSink
Generating Sqlite3 output for class Async::AudioSink
sqlite3_step failed: NOT NULL constraint failed: derivedcompoundref.derived
Generating Sqlite3 output for class Async::AudioSource
Generating Sqlite3 output for class Async::AudioSource
sqlite3_step failed: NOT NULL constraint failed: derivedcompoundref.base
Generating Sqlite3 output for class EchoLink::Dispatcher::ConData
Generating Sqlite3 output for class EchoLink::Dispatcher::ConData
Generating Sqlite3 output for class EchoLink::Directory
Generating Sqlite3 output for class EchoLink::Directory
unable to read file loc from[EchoLink::StationData::statusStr]
Generating Sqlite3 output for class EchoLink::Dispatcher
Generating Sqlite3 output for class EchoLink::Dispatcher
Generating Sqlite3 output for class EchoLink::Proxy
Generating Sqlite3 output for class EchoLink::Proxy
Generating Sqlite3 output for class EchoLink::Qso
Generating Sqlite3 output for class EchoLink::Qso
Generating Sqlite3 output for class EchoLink::Qso::RawPacket
Generating Sqlite3 output for class EchoLink::Qso::RawPacket
Generating Sqlite3 output for class EchoLink::StationData
Generating Sqlite3 output for class EchoLink::StationData
unable to read file loc from[EchoLink::StationData::status]
unable to read file loc from[EchoLink::StationData::setStatus]
unable to read file loc from[EchoLink::StationData::statusStr]
unable to read file loc from[EchoLink::StationData::statusStr]
unable to read file loc from[EchoLink::Directory::statusStr]
unable to read file loc from[EchoLink::StationData::time]
unable to read file loc from[EchoLink::StationData::setTime]
unable to read file loc from[EchoLink::StationData::id]
unable to read file loc from[EchoLink::StationData::setId]
unable to read file loc from[EchoLink::StationData::ip]
unable to read file loc from[EchoLink::StationData::setIp]
Generating Sqlite3 output for class sigc::trackable
Generating Sqlite3 output for class sigc::trackable
sqlite3_step failed: NOT NULL constraint failed: derivedcompoundref.base
sqlite3_step failed: NOT NULL constraint failed: derivedcompoundref.base
sqlite3_step failed: NOT NULL constraint failed: derivedcompoundref.base
sqlite3_step failed: NOT NULL constraint failed: derivedcompoundref.base
Generating Sqlite3 output for class EchoLink::Qso::VoicePacket
Generating Sqlite3 output for class EchoLink::Qso::VoicePacket
Generating Sqlite3 output for namespace EchoLink
Generating Sqlite3 output for file EchoLinkDirectory.h
Generating Sqlite3 output for file EchoLinkDispatcher.h
Generating Sqlite3 output for file EchoLinkProxy.h
Generating Sqlite3 output for file EchoLinkQso.h
Generating Sqlite3 output for file EchoLinkStationData.h
Generating Sqlite3 output for file mainpage.dox
Generating Sqlite3 output for dir /usr/src/svxlink/src/build/include/
Generating Sqlite3 output for example EchoLinkDirectory_demo.cpp
Generating Sqlite3 output for example EchoLinkDispatcher_demo.cpp
Generating Sqlite3 output for example EchoLinkProxy_demo.cpp
Generating Sqlite3 output for example EchoLinkQso_demo.cpp
Generating Sqlite3 output for the main page
lookup cache used 437/65536 hits=1935 misses=456

**Comment by sm0svx** [comment]
Isn't this the same issue as #168?

**Comment by sm0svx** [comment]
It is kind of hard to maintain a Doxygen configuration that work on all ranges of linux distributions. As long as it's only warnings we may have to live with them to be compatible over a wide range of distributions. However, it has been a while since I updated the config so the situation can possibly be somewhat improved.

**Comment by sm0svx** [comment]
Doxygen warnings fixed in latest master as far as possible
