### ISSUE TITLE
Latest Version - error in compile, version conflict

### ISSUE THREAD

**Issue by f5vmr** [sm0svx/svxlink#175]
I have cloned the latest version, but the modules EchoLink etc produce errors indicating that were compiled for version 1.4.99.2 when SVXlink is version 1.4.99.32. Did I miss something vital? Or was this a missed event in the drive to expedite the Debian issue before the deadline of termination?

pi@f5zgm ~ $ sudo svxlink
SvxLink v1.4.99.32 (Nov  4 2015) Copyright (C) 2003-2015 Tobias Blomberg / SM0SVX

SvxLink comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
welcome to redistribute it in accordance with the terms and conditions in the
GNU GPL (General Public License) version 2 or later.

Using configuration file: /etc/svxlink/svxlink.conf
--- Using sample rate 48000Hz

Starting logic: RepeaterLogic
Loading RX: Voter
        Adding receiver: Rx1
        Adding receiver: Net1Trx
Loading TX: MultiTx
        Adding transmitter: Tx1
        Adding transmitter: TxStream
Loading module "ModuleHelp" into logic "RepeaterLogic"
        Found /usr/lib/svxlink/ModuleHelp.so
        Module Help v1.0.0 starting...
*** ERROR: This module is compiled for version 1.4.99.2 of SvxLink but the running version of the SvxLink core is 1.4.99.32.
*** ERROR: Initialization failed for module ModuleHelp in logic RepeaterLogic
Loading module "ModuleParrot" into logic "RepeaterLogic"
*** ERROR: Failed to load module ModuleParrot into logic RepeaterLogic: /usr/lib/svxlink/ModuleParrot.so: undefined symbol: _ZN5Async5TimerC1EiNS0_4TypeE
Loading module "ModuleEchoLink" into logic "RepeaterLogic"
*** ERROR: Failed to load module ModuleEchoLink into logic RepeaterLogic: /usr/lib/svxlink/ModuleEchoLink.so: undefined symbol: _ZN5Async5TimerC1EiNS0_4TypeE
Loading module "ModuleMetarInfo" into logic "RepeaterLogic"
        Found /usr/lib/svxlink/ModuleMetarInfo.so
        Module MetarInfo v1.0.0.99.0 starting...
*** ERROR: This module is compiled for version 1.4.99.2 of SvxLink but the running version of the SvxLink core is 1.4.99.32.
*** ERROR: Initialization failed for module ModuleMetarInfo in logic RepeaterLogic
Loading module "ModulePropagationMonitor" into logic "RepeaterLogic"
        Found /usr/lib/svxlink/ModuleTcl.so
        Module Tcl v1.0.1 starting...
*** ERROR: This module is compiled for version 1.4.99.2 of SvxLink but the running version of the SvxLink core is 1.4.99.32.
*** ERROR: Initialization failed for module ModulePropagationMonitor in logic RepeaterLogic
RepeaterLogic: Event handler script successfully loaded.

Starting logic: NetLogic
Loading RX: Net1Rx
Loading TX: Net1Tx
NetLogic: Event handler script successfully loaded.
Activating link LinkToServer
192.168.0.100:5210: RemoteTrx protocol version 2.4
Net1Rx: Connected to remote receiver at 192.168.0.100:5210
Net1Rx: Requesting CODEC "S16"
Net1Tx: Connected to remote transmitter at 192.168.0.100:5210
Net1Tx: Requesting CODEC "S16"
Tx1: Turning the transmitter ON
TxStream: Turning the transmitter ON
172.20.1.6:19123: RemoteTrx protocol version 2.4
Net1Trx: Connected to remote receiver at 172.20.1.6:19123
Net1Trx: Requesting CODEC "S16"
Net1Tx: The transmitter is ON
Net1Rx: The squelch is OPEN (1)
Net1Rx: The squelch is CLOSED (0)
TxStream: Turning the transmitter OFF
Tx1: Turning the transmitter OFF
Net1Tx: The transmitter is OFF
Voter: The squelch is OPEN (Rx1=8.63463)
Voter: The squelch is CLOSED (Rx1=-0.732708)
Voter: The squelch is OPEN (Rx1=8.07195)
Voter: The squelch is CLOSED (Rx1=0.450445)
Voter: The squelch is OPEN (Rx1=10.3167)
Voter: The squelch is CLOSED (Rx1=-1.63228)

SIGINT received. Shutting down application...
pure virtual method called
terminate called without an active exception
pi@f5zgm ~ $

**Comment by sm0svx** [comment]
The installation path for SvxLink modules are now autodetected and depend on the architecture. The installation path has probably changed on your system so you are using the old modules with the new code.

You should remove the old modules in whatever directory MODULE_PATH point to. Then uncomment the MODULE_PATH config variable and SvxLink will find the correct path on its own.

**Comment by f5vmr** [comment]
As you correctly pointed out, I deleted the older files, commented out the modules location in SVXlink.conf and rebooted. F5ZGM is in full operation once again. Thanks Tobias.
You may close the issue unless you think it may benefit others who choose to update.
