### ISSUE TITLE
Async Issue in latest version

### ISSUE THREAD

**Issue by f5vmr** [sm0svx/svxlink#181]
svxlink: /home/pi/svxlink/src/async/audio/AsyncAudioSource.cpp:168: int Async::AudioSource::sinkWriteSamples(const float*, int): Assertion `len > 0' failed.

Running a new simple repeater, and in testing the audio with ModuleParrot engaged and called for by DTMF and running SvxLink in direct mode (not Daemon) this error is shown in the log list, the repeater locks in transmit and the raspberry no longer responds to command line entries.

In Daemon mode, and not calling for ModuleParrot, the repeater remains active until about the eight opening of the squelch and locks up. I have not noticed this in the active repeaters in service yet.

The previous versions had no issues in this regard. Any ideas please?

Chris

**Comment by f5vmr** [comment]
Today stupidity has entered the game - Somehow RepeaterLogic.tcl got deleted from my local folder.
Ignore this post.

**Comment by sm0svx** [comment]
SvxLink should not crash just because a file is missing so I'd say this is still a bug. Is it easy to reproduce?

**Comment by f5vmr** [comment]
Oh yes very easy. Especially when one deleted the whole of the svxlink directory in error. Works fine after a rebuild. Silly me!
Chris.

**Comment by sm0svx** [comment]
An application should never throw an assertion like that unless there is a programming error in the application. Broken builds could also cause such errors but missing configuration files should never cause an assertion failure.

So, just to be clear, what directory did you delete? There are many directories called svxlink (/etc/svxlink, /usr/share/svxlink, the svxlink source/build directory etc).

Did you delete the directory while SvxLink was running?

**Comment by f5vmr** [comment]
Fortunately it was a repeater under construction and not in service. I deleted the whole of the SVXLink directory containing the src etc. So when I set the repeater to run, there were no longer any cpp files to be called. That simple. Complete and utter human error. Marked down as a fail - Doh! 
No worries on the software, as I recompiled from scratch - and it works. I won't be doing that again!
Regards, Chris

**Comment by sm0svx** [comment]
OK. We'll call it a user error for now then :-)

As a note, the cpp files are not "called" after SvxLink has been built. The build process translate the cpp source files into machine code, present in the svxlink binary and in the .so files. The source files are not needed after that.

**Comment by f5vmr** [comment]
Problem has not gone away - Transmitter remains on as the SVXlink crashes with this error. This is the latest git clone on a Raspberry PI B+ on 8 Gb SD Card. I cannot see anything that I have wrong.

svxlink: /home/pi/svxlink/src/async/audio/AsyncAudioSource.cpp:168: int Async::AudioSource::sinkWriteSamples(const float*, int): Assertion `len > 0' failed.

Any pointers would be gratefully received.

Chris

**Comment by hb9pae** [comment]
Hello all

I do have the same error as f5mvr noted above.  (Raspberry PI, USB Soundcard, svxlink V 1.5.0)

> _svxlink: /home/pi/svxlink/src/async/audio/AsyncAudioSource.cpp:168: int 
> Async::AudioSource::sinkWriteSamples(const float*, int): Assertion `len > 0' failed.

How to solve this error? 

Thanks for any suggestion.

73 de Peter HB9PAE

**Comment by f5vmr** [comment]
Just updating this situation. there is no change with this install. It is the only one that is doing it. When it crashes no errors are reported directly. I had to make a bash script that detected the crash, printing the error and restarting SVXLink. I have swapped USB Audio cards, updated the software, and checked the configuration files. So for the moment this is a bug.
