### ISSUE TITLE
SVXlink metarinfo stopped working having previously been fully functional...

### ISSUE THREAD

**Issue by g4usp** [sm0svx/svxlink#205]
I have SVXlink running as a repeater controller with all modules available. All modules are fully functional with the exception of metarinfo which having previously worked now reports "xxxx metar information not valid" any idea's?

**Comment by dl1hrc** [comment]
look here:

https://github.com/sm0svx/svxlink/issues/189

Am 14.08.2016 um 14:40 schrieb Simon:

**Comment by citynetcomputing** [comment]
Hi,

Yes, noaa changed their website which effects the hard coded "weather.noaa.gov" address in the metarinfo so binary. You have two options:

1. Edit and recompile the SO with the address and sub directories changed to the following:
http://tgftp.nws.noaa.gov/data/observations/metar/stations/

2. This is what i did on raspbian, install apache2 and create the above directory structure in it. Add weather.noaa.gov to /etc/hosts pointing to 127.0.0.1. Write a cron script to grab the http://tgftp.nws.noaa.gov/data/observations/metar/stations/LOC.TXT script and drop it in that folder.

Works perfectly and plays all the metar info from the file. Mine is KBUF.TXT yours is whatever it is..

**Comment by sm0svx** [comment]
Adi's updated MetarInfo module is in Git master now

**Comment by dl1hrc** [comment]
Can I delete the branches "metarinfo_changed_service" and
"AsyncTcpBugfixes"?

Am 14.01.2017 um 16:46 schrieb Tobias Blomberg:

**Comment by sm0svx** [comment]
Yes, if you are satisfied with what I have merged
