### ISSUE TITLE
The module Frn does not connect to the backup server

### ISSUE THREAD

**Issue by dh9yap** [sm0svx/svxlink#206]
The ModuleFrn does not connect to the backup server if the primary server fails.
Maybe you can integrate this Future still with
73 55 dh9yap Jürgen

**Comment by sm0svx** [comment]
@sh123, what do you think?

**Comment by sh123** [comment]
Should be doable, need to add configuration option for backup server and fallback when main server retry count reaches maximum. Will try to find time and add it.

**Comment by dh9yap** [comment]
thank you for the information
73 55 de Jürgen DH9YAP
Please consider the following question 
ModuleFrn TX Hangtime too long #228

**Comment by sh123** [comment]
#229

**Comment by sm0svx** [comment]
PR #229 merged
