### ISSUE TITLE
Module activation on startup and 2 modules at the same time 

### ISSUE THREAD

**Issue by framar1** [sm0svx/svxlink#211]
would love to have it auto activate a module when it starts 
and would like to run the parrot and the metar at the same time 
maybe metar could announce weather on the long id string

**Comment by dl1hrc** [comment]
> would love to have it auto activate a module when it starts
> and would like to run the parrot and the metar at the same time
> maybe metar could announce weather on the long id string

running two module at the same time is not possible, sri.

**Comment by framar1** [comment]
what about auto activation of a module on start up IE:i run my node as a parrot repeater so i want parrot to run when the system starts without having to use dtmf to turn it on

**Comment by dl1hrc** [comment]
sri, no idea at the moment

Am 10.10.2016 um 09:09 schrieb framar1:

**Comment by kb3vgw** [comment]
you add them to the svxlink.conf and then you have to use dtmf to activate the module. modules dont just activate .

**Comment by sm3sgp** [comment]
Specific announcements at id should be possible to add in the TCL scripts.
Activation of two modules at the same time will require major changes.

**Comment by hayden-t** [comment]
A very simple way to do this is to use the injectDtmf at the end of your logic tcls startup{} function , eg if you want to activate module number 1

injectDtmf 1#
