### ISSUE TITLE
segfault when building

### ISSUE THREAD

**Issue by kb3vgw** [sm0svx/svxlink#233]
[ 19%] Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncPty.cpp.o
cd /usr/src/svxlink-build/svxlink-15.99/build/async/core && /usr/bin/c++   -DINTERNAL_SAMPLE_RATE=16000 -D_REENTRANT -Dasynccore_EXPORTS -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -D_FORTIFY_SOURCE=2  -Wall -Wpointer-arith  -fPIC -I/usr/src/svxlink-build/svxlink-15.99/build/include -I/usr/src/svxlink-build/svxlink-15.99/build -I/usr/lib/arm-linux-gnueabihf/sigc++-2.0/include -I/usr/include/sigc++-2.0    -o CMakeFiles/asynccore.dir/AsyncPty.cpp.o -c /usr/src/svxlink-build/svxlink-15.99/src/async/core/AsyncPty.cpp
In file included from /usr/include/sigc++-2.0/sigc++/adaptors/lambda/lambda.h:25:0,
                 from /usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h:31,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:89,
                 from /usr/src/svxlink-build/svxlink-15.99/build/include/AsyncFdWatch.h:45,
                 from /usr/src/svxlink-build/svxlink-15.99/src/async/core/AsyncPty.cpp:53:
/usr/include/sigc++-2.0/sigc++/adaptors/lambda/operator.h:1:0: internal compiler error: Segmentation fault
 // -*- c++ -*-
 ^

**Comment by sm0svx** [comment]
SvxLink cannot be blamed for an internal error in the compiler. Please report the problem to the gcc project or the package maintainer for your distribution. Maybe the problem has been fixed in a later version of the compiler.
