### ISSUE TITLE
Echolink Auth problem 

### ISSUE THREAD

**Issue by sa2blv** [sm0svx/svxlink#243]
Seens latest fixes.
svxlink will complie module echolink 
but when i useing it i dosent connect to the 
svx servers. it works with previus compiled module
i tested it in a simplexlogic config 

// Peter DE SA2BLV

**Comment by sm0svx** [comment]
Working just fine here. Try to start over with a clean copy of the source code.

**Comment by sm0svx** [comment]
Oh, if you were talking about svxserver, I have not tested it. I have no config for it here since I don't use it myself. Ask @dl1hrc if you have problems with it.

**Comment by f5vmr** [comment]
I use it, don't forget to set the passwords at both ends.

**Comment by sa2blv** [comment]
the peolem sems to be in svxlink when it supouse to connect to the echolink server
i dosent get an answer from server and promt the echolink server. the build was clean new 
from git but cant make this to happen on an other system
