### ISSUE TITLE
Wideband Receiver cannot handle FQ_CORR=0

### ISSUE THREAD

**Issue by pe1chl** [sm0svx/svxlink#257]
When a wideband receiver is configured with FQ_CORR=0, the following error is logged continuously:
Sun Mar 19 14:23:39 2017: Found Rafael Micro R820T tuner
Sun Mar 19 14:23:39 2017: *** WARNING: Failed to set ppm error
Sun Mar 19 14:23:39 2017: WbRx1: Changed state to NOT READY
Setting e.g. FQ_CORR=1 fixes this.
We have replaced our cheap RTL-DVB sticks which usually show an error around 40 with RTL-SDR.COM sticks with TCXO and those often have an actual error of 0 or 1.

**Comment by sm0svx** [comment]
Thanks for reporting! Fixed in latest master.
It's actually an error directly from the rtlsdr library but now I don't try to set the fq_corr if it's configured to 0 in SvxLink.
