### ISSUE TITLE
DTMF decoder fails ITU-T Q.23 tests

### ISSUE THREAD

**Issue by dh1dm** [sm0svx/svxlink#261]
The current DTMF decoder fails both the accept and reject level tests for signals with noise.
I'd suggest to make the old sliding window based decoder availiable again via config option.

**Comment by sm0svx** [comment]
That's interesting but passing the tests is not as important as real-life performance. I guess the tests were designed for telephone use of DTMF but when being used in a ham radio environment there may be other things to optimize for. In my experience the current DTMF decoder performs better in the environment at hand. It responds quicker, it has much reduced false detections and it adapts to weak signal conditions.

The old decoder is still available by setting DTMF_DEC_TYPE=DH1DM so you can still use that if you prefer it.
