### ISSUE TITLE
SvxLinkWrapper - Extra programming interface in python

### ISSUE THREAD

**Issue by sm0svx** [sm0svx/svxlink#27]
**Reported by guysoft on 28 Jan 2012 00:15 UTC**
Hey,
I want to interface SvxLink to more smarter and flexible logic.
In order to do this, I am writing a wrapper around SvxLink's input and output, hence its called SVXlinkWrapper.

SVXlinkWrapper is written in python, the advantage of having a dynamic language at hand means one can do complex new additions to SvxLink using 3rd party libraries without needing to compile anything.

For now I coded an echolink qso logger, which logs all QSOs in an sqlite database (which I can display on the net here: http://gnet.homelinux.com/ham/R1).
Also an 'autoconnect' feature to other echolink nodes on startup, with a keepalive mode.

As this wrapper grows one could add more modules.

**Comment by PauloWolf** [comment]
Hi Tobias !

Can you help on building a module for GPT over SVXlink ?
Radio Ham sends dtmf to ativate, then ask via microphone for a question, GPT answers back via voice.

Best of all Regards !
