### ISSUE TITLE
SVXReflector send via events List of nodes

### ISSUE THREAD

**Issue by sp2ong** [sm0svx/svxlink#274]
It will be nice to have via event sources access to svxreflector list of joined nodes similar like in echolink module list of echolink nodes in procedure client_list_changed . I thing that we are need create ReleectorLogic.tcl in which will be "publishStatEvent Reflector:nodes ..."

73 Waldek

**Comment by sm0svx** [comment]
The Reflector probably will never have the event handling system but some other system to get information out. The Reflector is at a very early stage at the moment and as a fact it's not even released yet but just experimental. There are still some basic functionality to work on before adding more features.

**Comment by dl1hrc** [comment]
Would be nice to have the event handler in the ReflectorLogic though. Conceivable applications would be logbook's or to show the connected nodes on LCD-Display or to process the connections/messages on web pages. I fell it's better to have defined tcl procedures instead of grepping logfiles.

**Comment by sm0svx** [comment]
What would be better is some web API that can be used to get all sorts of information out from SvxLink. Using the event handler for this is a hack.

**Comment by sp2ong** [comment]
web API will be a nice tool to get all information but I think that Adi and Rob have more experiences with this task. At current, I have use script eventsources by Rob which allows read only one STATE PTY in the loop to display information. Maybe web API will allow collects in one time different information

**Comment by sm0svx** [comment]
A good web API would make all PTYs obsolete and is a more natural way for a web application to interact with SvxLink.
