### ISSUE TITLE
The announcement is heard twice when connected to the conference room.

### ISSUE THREAD

**Issue by baybar01** [sm0svx/svxlink#278]
I installed svxlink with ubuntu mate on raspberry.
Usb sound card and rs232 (with usb converter) trigger. No problem when connected with handset in normal calculation. In the conference room, however, the announcement is made twice.
How can I fix it.

**Comment by sm3sgp** [comment]
Not enough information and probably a configuration issue. Please use the groups.io mailing list for questions or to request help.
