### ISSUE TITLE
Build keeps failing... (error: call of overloaded ‘abs(unsigned int)’ is ambiguous)

### ISSUE THREAD

**Issue by clem16** [sm0svx/svxlink#284]
I have repeatedly attempted to build the project, it keeps failing at this point. 
Any suggestions?
This is being built on a fresh install of Arch.

[log.txt](https://github.com/sm0svx/svxlink/files/1053026/log.txt)

**Comment by sm0svx** [comment]
That problem seems to have appeared in newer versions of the compiler. The problem is now fixed in the master and svxreflector branch.

Even though the fabs approach may work I think it is more appropriate to cast the unsigned parameter to a signed integer.

**Comment by clem16** [comment]
Perfect! Thanks.
