### ISSUE TITLE
DTMF_CTRL_PTY Enhacement

### ISSUE THREAD

**Issue by DG1BBQ** [sm0svx/svxlink#293]
When sending a command through DTMF_CTRL_PTY you need to open the repeater by sending a star. The problem is the duality of the star command. If the repeater is closed, it will open it. If it's aready open, it will trigger proc manual_identification. To get around this, you have to check if the repeater is already open and if it is, you can send your command. Othewise you need to send a star first. Unfortunately, it frequently happens that the repeater has closed right after checking the state! This causes the command to be ignored due to the repeater being closed. I circumvented the problem by adding a condition to proc manual_identification that keeps it from playing when sending a command. Works fine, but it's not pretty.
I propose that the requirement to open the repeater by sending a star be dropped  when using DTMF_CTRL_PTY. The repeater should accept a command and take care of opening the repeater if necessary.
73s, Axel DG1BBQ

**Comment by sm0svx** [comment]
Fixed in the master branch
