### ISSUE TITLE
EchoLink.tcl: proc connected 

### ISSUE THREAD

**Issue by DG1BBQ** [sm0svx/svxlink#295]
proc connected is not passed the callsign of the station that was connected. This is a problen, when using an external connect logic to connect to more than one station. You can't tell which station was just succsessfully connected. The way I worked around this, was to connect again, suppressing the 'already connected" anouncement and then receiving 'already connected' through publishStateEvent to confirm the connect.

I  propose that proc connected should be passed the callsign of the connected station

73s, Axel DG1BBQ

**Comment by sm0svx** [comment]
Fixed in the master branch
