### ISSUE TITLE
How to disble echolink commands ## 

### ISSUE THREAD

**Issue by sp2ong** [sm0svx/svxlink#305]
Hi,

How to disable echolink modules commands # and ## ??
I have tried :
 if {$active_module == "EchoLink"} {
  if {[string length $cmd] < 4 && [string index $cmd 0] == "#"} {
      puts "Ignoring # command for module EchoLink: $cmd"
      return 1
    }
  }

but without success.

I need to disable this command temporary during retransmission bulletins via our local echolink node

73 Waldek

**Comment by sm0svx** [comment]
See answer on mailing list
