### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by iw0red** [sm0svx/svxlink#309]
1003.011834] perf interrupt took too long (2555 > 2500), lowering kernel.perf_event_max_sample_rate to 50000
[ 2349.700680] perf interrupt took too long (5031 > 5000), lowering kernel.perf_event_max_sample_rate to 25000
[11790.654873] perf interrupt took too long (10006 > 10000), lowering kernel.perf_event_max_sample_rate to 12500

73 Marco IW0RED

**Comment by sm0svx** [comment]
It's normal. See [this post on the Arch forum](https://bbs.archlinux.org/viewtopic.php?id=187636) for example.
