### ISSUE TITLE
Compiling Warnings on Raspberry Pi Debian Stretch

### ISSUE THREAD

**Issue by dl1esk** [sm0svx/svxlink#311]
After upgrading my Raspbian Jessie to Raspbian Stretch i get the following Compiling Warnings...
Any Ideas ?!

47%] Building CXX object locationinfo/CMakeFiles/locationinfo.dir/AprsTcpClient.cpp.o
In file included from /home/svxlink/src/locationinfo/AprsTcpClient.cpp:58:0:
/home/svxlink/src/build/include/common.h:146:6: warning: ‘bool SvxLink::setValueFromString(ValueType&, const string&) [with ValueType = std::__cxx11::basic_string<char>]’ defined but not used [-Wunused-function]
 bool setValueFromString(std::string &val, const std::string &str)
      ^~~~~~~~~~~~~~~~~~

53%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/LocalTx.cpp.o
In file included from /home/svxlink/src/svxlink/trx/LocalTx.cpp:70:0:
/home/svxlink/src/build/include/common.h:146:6: warning: ‘bool SvxLink::setValueFromString(ValueType&, const string&) [with ValueType = std::__cxx11::basic_string<char>]’ defined but not used [-Wunused-function]
 bool setValueFromString(std::string &val, const std::string &str)
      ^~~~~~~~~~~~~~~~~~

**Comment by dl1esk** [comment]
also...

 59%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/SquelchEvDev.cpp.o
In file included from /home/svxlink/src/svxlink/trx/SquelchEvDev.cpp:52:0:
/home/svxlink/src/build/include/common.h:146:6: warning: ‘bool SvxLink::setValueFromString(ValueType&, const string&) [with ValueType = std::__cxx11::basic_string<char>]’ defined but not used [-Wunused-function]
 bool setValueFromString(std::string &val, const std::string &str)

**Comment by sm0svx** [comment]
Yes, I know about that one. It's a "feature" of newer compiler versions. It is harmless but of course should be fixed. If it annoys you, you can disable the printout using:
```
cmake -DCMAKE_CXX_FLAGS=-Wno-unused-function ..
make
```

**Comment by sm0svx** [comment]
Fixed in latest master
