### ISSUE TITLE
Callsign search

### ISSUE THREAD

**Issue by JoelMon** [sm0svx/svxlink#314]
Would like to request a feature to be able to search for a callsign. Currently having to scroll down the alphabetical callsign list to find a station/link is annoying.

Thanks!

**Comment by reald** [comment]
:+1:. Also search for echolink number would be great. :-)

**Comment by sm0svx** [comment]
I guess you are talking about Qtel here?

Try to just type the start of the callsign you want to search for. Focus need to be on the station list. Not possible to search on EchoLink numeric ID though.

**Comment by sm3sgp** [comment]
The search callsign should work in Qtel with the answer from sm0svx.
