### ISSUE TITLE
WARNING: Illegal WAV file header. ChunkSize should be Subchunk2Size plus 36

### ISSUE THREAD

**Issue by sp2ong** [sm0svx/svxlink#316]
I have use tools audacity to create wav files with local information and time to time I have to see in svxlink log

WARNING: Illegal WAV file header. ChunkSize should be Subchunk2Size plus 36

What is reason generate this message by svxlink ??.  I have played this wav file via sox player without problem, but svxlink don't want play this file

soxi meteo.wav 

Input File     : 'meteo.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:17.49 = 279918 samples ~ 1312.12 CDDA sectors
File Size      : 560k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM

73 Waldek

**Comment by sm0svx** [comment]
Your file failed because it contained RIFF/WAV subchunks (LIST and id3) that SvxLink did not know about. That is to be considered a bug since a properly implemented RIFF parser should just ignore unknown subchunks. That have been fixed in latest master.

**Comment by sp2ong** [comment]
Tobias 
I have use svxreflector and this update is not available for this branch. Cna you update this changes in svxreflector branch ???
Thank you

Waldek

**Comment by sm0svx** [comment]
Done

**Comment by sp2ong** [comment]
Thanks

**Comment by sp2ong** [comment]
I have to try compile in branch svxreflectro but:

[ 72%] Building CXX object svxlink/svxlink/CMakeFiles/svxlink.dir/MsgHandler.cpp.o
/home/sp2ong/src/svxlink/src/svxlink/svxlink/MsgHandler.cpp: In member function ‘virtual bool WavFileQueueItem::initialize()’:
/home/sp2ong/src/svxlink/src/svxlink/svxlink/MsgHandler.cpp:754:22: error: ‘errno’ was not declared in this scope
          << strerror(errno) << endl;
                      ^
/home/sp2ong/src/svxlink/src/svxlink/svxlink/MsgHandler.cpp:790:24: error: ‘errno’ was not declared in this scope
            << strerror(errno) << endl;
                        ^
/home/sp2ong/src/svxlink/src/svxlink/svxlink/MsgHandler.cpp:817:26: error: ‘errno’ was not declared in this scope
              << strerror(errno) << endl;
                          ^
/home/sp2ong/src/svxlink/src/svxlink/svxlink/MsgHandler.cpp:843:28: error: ‘errno’ was not declared in this scope
                << strerror(errno) << endl;
                            ^
/home/sp2ong/src/svxlink/src/svxlink/svxlink/MsgHandler.cpp:895:28: error: ‘errno’ was not declared in this scope
                << strerror(errno) << endl;
                            ^
/home/sp2ong/src/svxlink/src/svxlink/svxlink/MsgHandler.cpp:930:43: error: ‘errno’ was not declared in this scope
          << filename << "\":" << strerror(errno) << endl;
                                           ^
/home/sp2ong/src/svxlink/src/svxlink/svxlink/MsgHandler.cpp: In member function ‘virtual int WavFileQueueItem::readSamples(float*, int)’:
/home/sp2ong/src/svxlink/src/svxlink/svxlink/MsgHandler.cpp:954:44: error: ‘errno’ was not declared in this scope
          << filename << "\": " << strerror(errno) << endl;
                                            ^
/home/sp2ong/src/svxlink/src/svxlink/svxlink/MsgHandler.cpp: In member function ‘virtual void WavFileQueueItem::unreadSamples(int)’:
/home/sp2ong/src/svxlink/src/svxlink/svxlink/MsgHandler.cpp:978:44: error: ‘errno’ was not declared in this scope
          << filename << "\": " << strerror(errno) << endl;
                                            ^
svxlink/svxlink/CMakeFiles/svxlink.dir/build.make:60: polecenia dla obiektu 'svxlink/svxlink/CMakeFiles/svxlink.dir/MsgHandler.cpp.o' nie powiodły się
make[2]: *** [svxlink/svxlink/CMakeFiles/svxlink.dir/MsgHandler.cpp.o] Błąd 1
CMakeFiles/Makefile2:1327: polecenia dla obiektu 'svxlink/svxlink/CMakeFiles/svxlink.dir/all' nie powiodły się
make[1]: *** [svxlink/svxlink/CMakeFiles/svxlink.dir/all] Błąd 2
Makefile:137: polecenia dla obiektu 'all' nie powiodły się
make: *** [all] Błąd 2

**Comment by sp2ong** [comment]
You can see exactly the same problem with compile in:
https://travis-ci.org/sm0svx/svxlink/jobs/297287362

**Comment by sm0svx** [comment]
Fixed. Try again.

**Comment by sp2ong** [comment]
Ok, Thank you. Now I have success with compile on Orange Pi Zero and HP 5730. I will try to use wav file to play via svxlink which generate the problem.

**Comment by sp2ong** [comment]
The wav file which previously generated problem now was played without problem
Thank you for fixed problem with wav filles

73 Waldek
