### ISSUE TITLE
svxlink hang when using automatic disconnect from svxreflector and station is talking

### ISSUE THREAD

**Issue by dl7ata** [sm0svx/svxlink#323]
Hi Tobias,
we use cronjob connects and disconnects for netlink connections into our svxreflector system.
So for example on saturday at 14:02 the netlink will be disconnect by
02 14 * * 6 /bin/echo "*930#" > /tmp/svx_pty.RemoteLogic
command. When at that certain time somebody is talking on netlink, on both of my logics - 2m and 70cm - the PTT is permanently on and runs after several minutes into timeout. After that, I have to restart svxlink. Would be great, If you can solve that issue.
Thanks, Frank

**Comment by sm0svx** [comment]
That's not good. Thanks for reporting. I have not tested much enabling/disabling the link. I'll have a look at it.

**Comment by sm0svx** [comment]
Found a bug in a pretty central audio component, the Async::AudioSelector. Fixed in latest Git master.

**Comment by dl7ata** [comment]
Thanks for your great support!

Have a nice x-mast time Tobias.

 

Best

Frank

 

Von: Tobias Blomberg [mailto:notifications@github.com] 
Gesendet: Montag, 4. Dezember 2017 16:49
An: sm0svx/svxlink
Cc: DL 7 ATA; Author
Betreff: Re: [sm0svx/svxlink] svxlink hang when using automatic disconnect from svxreflector and station is talking (#323)

 

Closed #323 <https://github.com/sm0svx/svxlink/issues/323> .
