### ISSUE TITLE
Remotetrx audio problem

### ISSUE THREAD

**Issue by ON4BIV** [sm0svx/svxlink#341]
Dear all,
I am already long time trying to set-up an svxlink-server/remotetrx configuration. The problem is that the audio local received on the remotetrx is transmitted on the remotestation and the svxlink-server station. The audio received on the svxlink-server-station is transmitted by the svxlink-server-station but not transmitted by the remotestation despite the PTT is working. On the screen output of the remotetrx is the following noted:
SetMuteState (CONTENT)
Turning the transmitter on

After the squels is closed:
Turning the transmitter off
SetMuteState (NONE)

Is there some-one who kan help me?

Chris
ON4BIV

**Comment by sm3sgp** [comment]
Please use the mailinglist for configuration and troubleshooting questions.  #384
