### ISSUE TITLE
 svxlink 1.5.99.17  aborted AsyncAudioDeviceAlsa.cpp

### ISSUE THREAD

**Issue by sp2ong** [sm0svx/svxlink#342]
Hi

I have compiled latest svxlink on puppy slacko 6.3.2 (compatible with Slackware 14.1) and 
after a few hours running I have seen on screen that svxlink stoped with info on screen:

svxlink: /usr/src/svxlink/src/async/audio/AsyncAudioDeviceAlsa.cpp:439: void Async::AudioDeviceAlsa::audioReadHandler(Async::FdWatch*, short unsigned int): Assertion `frames_read == frames_avail' failed.
Aborted

**Comment by sm0svx** [comment]
Try now with latest master

**Comment by sp2ong** [comment]
Hi Tobias

It looks that now not appear the problem. I have monitoring svxlink one day.
