### ISSUE TITLE
close short_identification during qso ?

### ISSUE THREAD

**Issue by f5swb** [sm0svx/svxlink#348]
Hi eveybody, 

I would like to know if it's possible to switch off the short identification during a qso on the air ?
I try FX_GAIN_LOW = -100 but only the first letter is heard not the next letters of the call ...
Any idea ?
many thanks in advance to all.
73's F5SWB/Dimitri.
svxlink 15.99.8 svxreflector.

**Comment by f5vmr** [comment]
Hi Dimitri, in svxlink.conf simply make the short item time=0. However in F5ZGM-R the level of all fx is -15 while active, it can still be heard but only very faintly.

**Comment by f5swb** [comment]
Many thanks chris for your quickly answer !


________________________________
De : Chris F5VMR <notifications@github.com>
Envoyé : vendredi 19 janvier 2018 18:27
À : sm0svx/svxlink
Cc : f5swb; Author
Objet : Re: [sm0svx/svxlink] close short_identification during qso ? (#348)


Hi Dimitri, in svxlink.conf simply make the short item time=0. However in F5ZGM-R the level of all fx is -15 while active, it can still be heard but only very faintly.

**Comment by sm0svx** [comment]
@f5swb, are you saying that if you set FX_GAIN_LOW=-100, while someone is speaking you will still hear the first letter of the callsign but not the rest?

**Comment by f5swb** [comment]
Yes my call is F5ZAU and I Heard only the F It's very strange isn't it ?

Envoyé de mon iPhone

Le 20 janv. 2018 à 12:34, Tobias Blomberg <notifications@github.com<mailto:notifications@github.com>> a écrit :


@f5swb<https://github.com/f5swb>, are you saying that if you set FX_GAIN_LOW=-100, while someone is speaking you will still hear the first letter of the callsign but not the rest?

**Comment by sm0svx** [comment]
Strange indeed... I'll mark this issue as a bug.

**Comment by sm0svx** [comment]
@f5swb: It seems to work perfectly here. No part of the callsign is heard if I set FX_GAIN_LOW=-100. Tested with a standard RepeaterLogic.

You seem to be running a non-standard version of SvxLink. 15.99.8 have not been released by the SvxLink project. The latest release is 17.12.1. When running non-standard versions you need to contact the people who released that version or switch to using an official SvxLink release.

**Comment by f5swb** [comment]
Hello sm0svx, in fact it works well with -100. 
Don't know why one time it didn't work ....

Many thanks.
