### ISSUE TITLE
svxlink: Libgcrypt warning: missing initialization - please fix the application

### ISSUE THREAD

**Issue by f4gbv** [sm0svx/svxlink#364]
Hello, could you help me with this please?
thanks
f4gbv:)

**Comment by f5vmr** [comment]
Have you installed this?
sudo apt install libgcrypt20-dev
If not , then perform this then reperform your cmake line.

**Comment by sm0svx** [comment]
@f4gbv, which version of SvxLink are you running?  Which Linux-distribution/version?
