### ISSUE TITLE
CW::play - amplitude parameter did'nt change

### ISSUE THREAD

**Issue by dl7ata** [sm0svx/svxlink#366]
I cant change the amplitude in dB in tcl-command CW::play.
I played around with `CW::play $mycall 120 330 -120` ,  but changing the -120 up to 0 doesn't effect something.
When I switch back to the old amplitude param `CW::play $mycall 120 330 72;
,` its working with that message
`15.02.2018 09:15:00: *** WARNING: Deprecated CW amplitude specification: 12.
15.02.2018 09:15:00:              Use the equivalent -38.42 (dB) instead.
`

**Comment by dl1esk** [comment]
Amplitude is from 0 to 10 20 30 40 50 60 70 80 90 etc...
it`s working

**Comment by dl7ata** [comment]
Thats what I wrote: 

> the old amplitude param CW::play $mycall 120 330 72; , is working

Tobias changed it into dB equivalent, which means you have to use negative values. This won't work here.

**Comment by sm0svx** [comment]
Obviously I did not test using dB values in the CW::play function but now it should work in latest master,
