### ISSUE TITLE
Refresh manual online

### ISSUE THREAD

**Issue by Dloranger** [sm0svx/svxlink#368]
I frequently point others to this page as a quick online reference for some of the features of svxlink.

svxlink.sourceforge.net/man/man5/svxlink.conf.5.html

Can you refresh this page or have it redirect to something that is maintained?

**Comment by sm0svx** [comment]
Don't use the manual pages from the old SourceForge site. They should be removed. Use the [manual page on GitHub](http://www.svxlink.org/doc/man/man5/svxlink.conf.5.html) instead. I'll see if I can get a redirect in place.

**Comment by sm0svx** [comment]
All manual pages on the SourceForge web site should now have redirects to www.svxlink.org.
