### ISSUE TITLE
Segmentation Fault when trying to connect to Echolink Node

### ISSUE THREAD

**Issue by McPeebs** [sm0svx/svxlink#371]
Hi,

I am unable to connect to Echolink nodes. I am getting a segmentation fault and then SVXlink terminates. When I restart SVXlink, it gives me a Seg Fault error 2 to 3 more times, then on the fourth attempt the program will launch, but will still Seg fault when connecting to a Echolink node.

Anyone else had this issue? 

SimplexLogic: Macro command found: "EchoLink:9999#"
SimplexLogic: Activating module EchoLink...
DTMF command received in module EchoLink: 9999
Connecting to *ECHOTEST* (9999)
Tx1: Turning the transmitter ON
*ECHOTEST*: EchoLink QSO state changed to CONNECTING
Tx1: Turning the transmitter OFF
Segmentation fault

**Comment by sm0svx** [comment]
Which version are you running?  Latest release (17.12.1) or latest git master?  On what hardware?  On what linux distribution?

**Comment by sm3sgp** [comment]
@McPeebs Do you have more information on this issue?
