### ISSUE TITLE
SvxLink Error - Trying to update the directory list while not registered with the directory server

### ISSUE THREAD

**Issue by GeoSchaedler3** [sm0svx/svxlink#374]
I am trying to get qtel EchoLink to work on my raspberry pi 3. I loaded and made the code correctly without errors, but when I try to use a public proxy I get this error:

Trying to update the directory list while not registered with the directory server

Does anyone encountered this error and is there a solution

**Comment by sm3sgp** [comment]
Please use the mailing list for this type of question. #384
