### ISSUE TITLE
version of the svxlink

### ISSUE THREAD

**Issue by VR2XKP** [sm0svx/svxlink#391]
Hello, I follow this guide to install the latest version of Svxlink 17.12.1-2 .

https://github.com/sm0svx/svxlink/wiki/InstallBinRaspbian

But when it run, it prompts the svxlink version is version 1.6 only. Does it normal ?

**Comment by sm3sgp** [comment]
Yes, this is normal.
The different applications, such as svxlink, remotetrx, siglevdetcal and others, have different version numbers. Have a look here:
https://github.com/sm0svx/svxlink/blob/maint/src/doc/README-17.12.adoc

**Comment by sm0svx** [comment]
Please use the [SourceForge mailing lists](https://sourceforge.net/p/svxlink/mailman/svxlink-devel) or [groups.io](https://groups.io/g/svxlink) to ask questions.
