### ISSUE TITLE
Enable CTCSS_TX via DTMF

### ISSUE THREAD

**Issue by ripice** [sm0svx/svxlink#406]
Hi,

I have to connect a repetear to a security system and i need to activate CTCSS of the TX via a emergency DTMF.

It is possible to generate a CTCSS tone on a TCL?

Thanks!!

**Comment by sm0svx** [comment]
Please use the [SourceForge mailing lists](https://sourceforge.net/p/svxlink/mailman/svxlink-devel) or [groups.io](https://groups.io/g/svxlink) to ask questions.

It is not possible to temporarily enable CTCSS transmission on a SvxLink transmitter. You could of course have it enabled all the time but that's not desirable I guess.
