### ISSUE TITLE
Discussion Forum

### ISSUE THREAD

**Issue by dl1esk** [sm0svx/svxlink#407]
Hi there,

i`m the operator of the German SvxLink Forum and i opened an english section of the Forum so that the english speaking people can discuss about problems there so that the issue tracker not longer be used as Forum. U can find the english section of the forum here:

https://forum.funk-telegramm.de/board/31-svxlink-forum-english/

73 Sebastian

**Comment by flyingdutchmen001** [comment]
wat doe je met systemen als je zelf geen LEES vaardigheden meer hebt=0

                                         💖

**Comment by flyingdutchmen001** [comment]
is opgelost  (  prullebak beschadigt )  opl = LEEGMAKEN !!!   😅

Op vr 24 aug. 2018 om 00:27 schreef Arjan Berends <notifications@github.com
