### ISSUE TITLE
Voice flickering.

### ISSUE THREAD

**Issue by iw0red** [sm0svx/svxlink#410]
Hi everyone,
sometimes when listen a qso from reflector, the voice was flickering. There wasn't networking issues at the time. It's a software bug?
73 Marco IW0RED

**Comment by iw0red** [comment]
I'm thinking...
It could be because the data send from svxlink to svxreflector and 
the other way around, comes on udp protocol, there is no guarantee of delivery, ordering or duplicate protection.
May be...

**Comment by RichNeese** [comment]
close

**Comment by sm0svx** [comment]
@iw0red, there already are checks for UDP packets being reordered or dropped. You should see entries in the logs telling you when that happens. Please reopen the issue if you still think it is a bug.
