### ISSUE TITLE
LocationInfo callsign

### ISSUE THREAD

**Issue by iw0red** [sm0svx/svxlink#416]
Hi everybody.
I'm trying to setup the aprs callsign IR6UAE-10 on the LocationInfo  section but doesn't work. This is the aprsc output:
14580	IR6UAE-10	79.37.60.132:60431	No	4m	4m	SvxLink 1.6.99.10	0	1/0/1	962	188	6.7 / 0	0	0	m/10.
73 Marco IW0RED

**Comment by sm0svx** [comment]
@iw0red, is this a bug?
