### ISSUE TITLE
I'm looking for svxlink image files 

### ISSUE THREAD

**Issue by catsilver** [sm0svx/svxlink#430]
Hello all
if you could kindly have the svxlink image file with the settings? many thanks.....

**Comment by dl1esk** [comment]
Tobias already said that this here is no discussion Forum please report only Bugs here !!!
Discussions or Questions here: https://forum.funk-telegramm.de/board/31-svxlink-forum-english/

**Comment by sm0svx** [comment]
This project will not publish images for a specific platform.
