### ISSUE TITLE
Issue with SVXLINK and onboard laptop sound card and external 

### ISSUE THREAD

**Issue by Rachidkar** [sm0svx/svxlink#438]
Good day
I am currently testing svxlink so as to put connect our repeater system to Echolink. I have downloaded and installed SVXLINK on a laptop running Ubuntu 16.04 TS. I am having issue with the onboard sound card.  It appears that SVXLink could not connect to the sound card. I went to buy a Sound Blaster Play! 2 USB audio and I am still having issues namely RX1.

I have searched the Internet for solutions and have tried a few but no success. 

Any help would be greatly appreciated

Rachd - 3B8FP

**Comment by sm0svx** [comment]
Please use the mailing list at SourceForge or the forum at groups.io to ask questions. Reopen issue if you think it's a bug in SvxLink.
