### ISSUE TITLE
Any idea why this is happening?

### ISSUE THREAD

**Issue by clem16** [sm0svx/svxlink#441]
Any idea why this is happening.?
Probably just missing something obvious...

`root@rpi:/usr/local/etc/svxlink # cat /dev/sndstat
Installed devices:
pcm0: <VCHIQ audio> (play)
pcm1: <USB audio> (play/rec) default
No devices installed from userspace.
`

`Using configuration file: /usr/local/etc/svxlink/svxlink.conf
--- Using sample rate 48000Hz

Starting logic: SimplexLogic
Loading RX: Rx1
SNDCTL_DSP_SETDUPLEX ioctl failed: Bad file descriptor
SNDCTL_DSP_GETCAPS ioctl failed: Bad file descriptor
Loading TX: Tx1
SimplexLogic: Event handler script successfully loaded.`

**Comment by sm0svx** [comment]
Please use the SourceForge mailing list or the forum at groups.io to ask questions. Reopen issue if you think it's a bug in SvxLink.
