### ISSUE TITLE
make fails, missing curl

### ISSUE THREAD

**Issue by Dloranger** [sm0svx/svxlink#449]
just tried to build trunk and got this

-- Found GCrypt: /usr/lib/arm-linux-gnueabihf/libgcrypt.so
-- Found RtlSdr: /usr/lib/arm-linux-gnueabihf/librtlsdr.so
-- Found Tclsh: /usr/bin/tclsh8.6 (found version "8.6")
-- Found TCL: /usr/lib/arm-linux-gnueabihf/libtcl8.6.so
-- Found DL: /usr/lib/arm-linux-gnueabihf/libdl.so
-- Could NOT find CURL (missing:  CURL_INCLUDE_DIR CURL_LIBRARY)
CMake Error at svxlink/svxlink/CMakeLists.txt:48 (message):
  Could not find the CURL library and development files.

-- Configuring incomplete, errors occurred!
See also "/root/svxlink/svxlink/src/build/CMakeFiles/CMakeOutput.log".
See also "/root/svxlink/svxlink/src/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'doc'.  Stop.
make: *** No rule to make target 'install'.  Stop.
Failed to enable unit: File svxlink.service: No such file or directory
Failed to disable unit: No such file or directory

checked and i have curl installed

root@openrepeater:~/scripts-2.1.x# apt-get install curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.52.1-5+deb9u9).
0 upgraded, 0 newly installed, 0 to remove and 64 not upgraded.

**Comment by dl1hrc** [comment]
> Could not find the CURL library and development files.
libcurl-**dev** is needed

**Comment by Dloranger** [comment]
better now, thanks Adi
