### ISSUE TITLE
TYPE=Local AUDIO_DEV=alsa:plughw:0 to Bluetooth ?

### ISSUE THREAD

**Issue by f5swb** [sm0svx/svxlink#453]
Hello, 

I'm trying to get the output sound of svxlink  to my bluetooth speaker ....
I can listen a sound with : 
aplay -D bluealsa:HCI=hci0,DEV=00:25:DB:80:D5:CC,PROFILE=a2dp solo_batterie_stereo.wav
Is there anyway to do the same wiht the trafic soound ?

Many thanks .

F5SWB.

**Comment by sm0svx** [comment]
Not a bug nor a feaure request. Please use the SourceForge mailing list or the forum at groups.io to ask questions.

You may get it to work if setting AUDIO_DEV="alsa:bluealsa:HCI=hci0,DEV=00:25:DB:80:D5:CC,PROFILE=a2dp".
