### ISSUE TITLE
Echolink connection problem ?

### ISSUE THREAD

**Issue by sp2ong** [sm0svx/svxlink#456]
Hi 

I observer many lines in log with the following problem with svxlink SvxLink release 17.12.2 -- 01 Mar 2018 (I have back to this version because latest sources from github have a problem: https://github.com/sm0svx/svxlink/issues/455 )

Sun May 19 11:07:33 2019: Spurious audio packet received from 44.137.75.243
Sun May 19 11:07:33 2019: Incoming EchoLink connection from SQ5TDR (Jacek) at 44.137.75.243
Sun May 19 11:07:33 2019: *** WARNING: Ignoring incoming connection from SQ5TDR since the IP address registered in the directory server (44.137.75.247) is not the same as the remote IP
 address (44.137.75.243) of the incoming connection
Sun May 19 11:07:34 2019: Spurious audio packet received from 44.137.75.243
Sun May 19 11:07:34 2019: Incoming EchoLink connection from SQ5TDR (Jacek) at 44.137.75.243

Most of the problems is with 44.137.75.xxx I don't have on svxlink server any link do 44-NET network.  

It looks similar problem like this: https://sourceforge.net/p/svxlink/mailman/message/32078579/

**Comment by sm0svx** [comment]
@sp2ong, is this still a problem?  Checking the IP address is a security feature. The IP address must be the same in the Echolink directory server as the IP address used for the UDP connections. If the client IP changes it may linger for a while in the Echolink servers so even if SvxLink refresh the list, the old IP may still be there. It should eventually correct itself.

Please reopen the issue if you still think it is a bug.
