### ISSUE TITLE
Requesting an updated released version

### ISSUE THREAD

**Issue by Dloranger** [sm0svx/svxlink#459]
As part of the Open Repeater project team, we would like to request an official release version update.

We only use the officially released "stable" version so our builds are consistent.  

We have been using the current version since early 2018, but a lot has been changed from this last version that we would like to bring into our builds. 

Much appreciated if we could get a fresh locked down revision.

**Comment by sm0svx** [comment]
Yes it's been too long (again). My intention is to get a release out soon.

**Comment by Dloranger** [comment]
@sm0svx Can we reopen this until we get an updated release? Going on 15 months since the last release

**Comment by Dloranger** [comment]
Reopening to get updated code into a released version
