### ISSUE TITLE
raspberrypi svxlink: Libgcrypt warning: missing initialization - please fix the application

### ISSUE THREAD

**Issue by f5swb** [sm0svx/svxlink#461]
hello, I'm running buster with the last svxlink git. 
All is ok but I have this in the svxling.log /var/log ?
raspberrypi svxlink: Libgcrypt warning: missing initialization - please fix the application
root@raspberrypi:~# sudo apt install libgcrypt20-dev
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
libgcrypt20-dev est déjà la version la plus récente (1.8.4-5). "already the newest version"
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.

any idea ?

73's F5SWB.

**Comment by dh9yap** [comment]
Hello ... do not understand the error ... is the error message in Svxlink.log to see?  and how does the error affect the operation of svxlink?  ... 73 Jürgen

**Comment by f5swb** [comment]
hello Jürgen , many thanks for rou answer
it does not affect the operation of svwlink, nothing in the svxlink.log about that 
I just found this in /var/log/user.log .... so I think that I shouldn't worry of it :)
