### ISSUE TITLE
svxlink echolink sysop -L call sign spelled  "dash lima"

### ISSUE THREAD

**Issue by jackskipper** [sm0svx/svxlink#464]
Hello,

I am new to svxlink. Just got the echolink running using svxlink on rasberry pi. It is intended to used as echolink sysop link.

One issue that I noticed is the call sign that I put with "-L" in the SimplexLogic under the svxlink conf is spelled as "dash lima" on identification announcement. For example, my call is W5BAY, I put it as W5BAY-L, the system will say "whisky five bravo alpha yankee **dash lima**"

I saw the event handler says play "link" if the callsign followed with  -L

Can anyone help me on this? 
How can I make svxlink spell my call sign with -L correctly as "W5BAY Link"? 
What do I need to type on the CALLSIGN= under the SimplexLogic

Thank you much.
Bayu - W5BAY

**Comment by sm0svx** [comment]
Hi Bayu and welcome to SvxLink. Please don't use this issue tracker to ask questions. It should strictly be used for bug reports and feature requests. Use the [SourceForge mailing lists](https://sourceforge.net/p/svxlink/mailman/) or the [groups.io](https://groups.io/g/svxlink) forum to ask questions.

SvxLink does not announce itself with the "link" designator on the RF channel. What you probaly saw in the TCL files is when SvxLink announces remote Echolink stations. You can tailor the announcements for your own needs by following the [instructions in the wiki](https://github.com/sm0svx/svxlink/wiki/InstallationInstructions#the-event-handling-subsystem).
