### ISSUE TITLE
Qtel UI: Where did everything go?

### ISSUE THREAD

**Issue by larsks** [sm0svx/svxlink#468]
I start with Qtel looking like this:

![Looks good](https://chunk.io/larsks/06cbbf80c8a246808a10109334f70587)

But when I quit and restart it, most of the UI elements have collapsed:

![Where did it go?](https://chunk.io/larsks/4297e70328c24ca89b822249ae961bb3)

This happens every time I start qtel.

qtel: v1.2.4
distribution: Fedora 30

**Comment by sm0svx** [comment]
Does not happen here on Fedora 31. The configuration is stored in ~/.config/SvxLink/Qtel.conf. Do you have some permission problem or something like that which stop Qtel from writing that file correctly?  Diskspace?

**Comment by sm0svx** [comment]
No feedback. Closing,
