### ISSUE TITLE
svxlink reflector_tg version warning during compile

### ISSUE THREAD

**Issue by sp2ong** [sm0svx/svxlink#470]
Hi Tobias,

During complie svxlink reflector_tg version on Raspbian v10 with update sources 15 October 
I have see warning:

[ 84%] Building CXX object svxlink/svxlink/CMakeFiles/svxlink.dir/DtmfDigitHandler.cpp.o
[ 84%] Building CXX object svxlink/svxlink/CMakeFiles/svxlink.dir/ReflectorLogic.cpp.o
In file included from /opt/src/svxlink/src/svxlink/svxlink/ReflectorLogic.cpp:60:
/opt/src/svxlink/src/svxlink/svxlink/../reflector/ReflectorMsg.h: In member function ‘virtual void ReflectorLogic::remoteReceivedPublishStateEvent(LogicBase*, const string&, const string&)’:
/opt/src/svxlink/src/svxlink/svxlink/../reflector/ReflectorMsg.h:994:22: warning: ‘*((void*)& rx +6)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
           m_flags = (m_flags & ~bit) | (is_enabled ? bit : 0);
                      ^~~~~~~
/opt/src/svxlink/src/svxlink/svxlink/../reflector/ReflectorMsg.h:994:22: warning: ‘*((void*)& rx +6)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
           m_flags = (m_flags & ~bit) | (is_enabled ? bit : 0);
                      ^~~~~~~
[ 85%] Linking CXX executable ../../bin/svxlink

**Comment by sm3sgp** [comment]
The reflector_tg is now merged to master.
This should be fixed.

**Comment by sp2ong** [comment]
yes, thank you
