### ISSUE TITLE
Macros to switch Talk Group

### ISSUE THREAD

**Issue by sp2ong** [sm0svx/svxlink#472]
I don't know that it is possible to define MACROS to switch Talk Group?

For exmaple:
[MacrosLink]
0:RepaterLogic:91260#
1:RepeaterLogic:91261#
...

Where RepeaterLogic is name of Logic LINKS

[ReflectorLink]
ONNECT_LOGICS=RepeaterLogic:9:SVXR,ReflectorLogic
 MACROS=MacrosLink
....

It will be easy to use D0# instead 91260# to switch Talk Group

**Comment by sm3sgp** [comment]
Try this:

0=:91260#
1=:91261#

**Comment by sp2ong** [comment]
Thanks,
