### ISSUE TITLE
SVXreflector no back compatibility?

### ISSUE THREAD

**Issue by sq4bja** [sm0svx/svxlink#480]
Hi,
I`m using SVXReflector from SVXLink verion 1.17.2. Now, i get newest svxlink client and i try to connect to older SVXReflector (1.17.2). It doesn`t work. Protocol error. The only way is upgrade every one by one repeater to newest SVXLink include finaly SVXReflector?
Tom SQ4BJA

**Comment by sm0svx** [comment]
The reflector server must be upgraded first, then all clients. The latest reflector server should be able to handle both old and current clients. Just be sure to set the TG_FOR_V1_CLIENTS in the new reflector config.
