### ISSUE TITLE
how to regenerate svxlink.conf?

### ISSUE THREAD

**Issue by mnjagadeesh** [sm0svx/svxlink#483]
Hi, I have mistakenly deleted svxlink.conf file. Is there anyway to regenerate it?

**Comment by f5vmr** [comment]
Hopefully you will still an original copy in the svxlink/source/build folder

Chris F5VMR / G4NAB

**Comment by Dloranger** [comment]
https://github.com/sm0svx/svxlink/blob/master/src/svxlink/svxlink/svxlink.conf.in

**Comment by mnjagadeesh** [comment]
I setup vagrant box in vagrant box and copied it from there. I used apt to install it.
