### ISSUE TITLE
Installation from .deb package and aptitude

### ISSUE THREAD

**Issue by oh3gai** [sm0svx/svxlink#486]
Hi!

First of all, you have done awesome work for repeater systems.

I'm not sure is this already know issue, but in ubuntu (16.04&18.04) sudo apt install svxlink-server and sudo dpkg -i fails if user is logged in as svxlink.  I.ve been strugling with this few days and  understood the problem today.

This isn't a real "bug", but may cause problems to those who are not so familiar with linux.

Thanks for great app and work for ham radio society.

Br. Jarno / OH3GAI

**Comment by sm0svx** [comment]
For security reasons you should normally not have sudo privileges for the user running SvxLink. One of the biggest reasons to use a separate user to run SvxLink is to lock it into its own world but if that user is allowed to run sudo commands you may open up a way to hack your system, especially if no password is required to run sudo.

Really, you should never be logged in as the svxlink user. It should only be used by the svxlink processes while they run.

That being said, the Debian packages are not maintained by the SvxLink project but is instead maintained by @lechner. Information for the package can be found here: https://tracker.debian.org/pkg/svxlink.
