### ISSUE TITLE
crash when missing CARD_CHANNELS=8 variable

### ISSUE THREAD

**Issue by Dloranger** [sm0svx/svxlink#502]
I am working on an 8 duplex system and I found that when this variable is missing, svxlink will start up okay, but then crash when the ports are attempted to be opened for Tx.  

I submit that this is a bug as the error comes after the system thinks it has successfully loaded up and is running.  This fault should be detected immediately and handled gracefully (either assume the highest number, or post an error to the logs for correction.

### Without the config variable

> Fri Jun 12 03:20:01 2020: SvxLink v1.7.0 Copyright (C) 2003-2019 Tobias Blomberg / SM0SVX
Fri Jun 12 03:20:01 2020:
Fri Jun 12 03:20:01 2020: SvxLink comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
Fri Jun 12 03:20:01 2020: welcome to redistribute it in accordance with the terms and conditions in the
Fri Jun 12 03:20:01 2020: GNU GPL (General Public License) version 2 or later.
Fri Jun 12 03:20:01 2020:
Fri Jun 12 03:20:01 2020: Using configuration file: /etc/svxlink/svxlink.conf
Fri Jun 12 03:20:01 2020: --- Using sample rate 48000Hz
Fri Jun 12 03:20:01 2020:
Fri Jun 12 03:20:01 2020: Starting logic: ORP_FullDuplexLogic_Port1
Fri Jun 12 03:20:01 2020: Loading RX: RX_Port1
Fri Jun 12 03:20:01 2020: Loading TX: TX_Port1
Fri Jun 12 03:20:01 2020: ORP_FullDuplexLogic_Port1: Event handler script successfully loaded.
Fri Jun 12 03:20:01 2020:
Fri Jun 12 03:20:01 2020: Starting logic: ORP_HalfDuplexLogic_Port2
Fri Jun 12 03:20:01 2020: Loading RX: RX_Port2
Fri Jun 12 03:20:01 2020: Loading TX: TX_Port2
Fri Jun 12 03:20:01 2020: ORP_HalfDuplexLogic_Port2: Event handler script successfully loaded.
Fri Jun 12 03:20:01 2020:
Fri Jun 12 03:20:01 2020: Starting logic: ORP_HalfDuplexLogic_Port3
Fri Jun 12 03:20:01 2020: Loading RX: RX_Port3
Fri Jun 12 03:20:01 2020: Loading TX: TX_Port3
Fri Jun 12 03:20:01 2020: ORP_HalfDuplexLogic_Port3: Event handler script successfully loaded.
Fri Jun 12 03:20:01 2020:
Fri Jun 12 03:20:01 2020: Starting logic: ORP_HalfDuplexLogic_Port4
Fri Jun 12 03:20:01 2020: Loading RX: RX_Port4
Fri Jun 12 03:20:01 2020: Loading TX: TX_Port4
Fri Jun 12 03:20:01 2020: ORP_HalfDuplexLogic_Port4: Event handler script successfully loaded.
Fri Jun 12 03:20:01 2020:
Fri Jun 12 03:20:01 2020: Starting logic: ORP_HalfDuplexLogic_Port5
Fri Jun 12 03:20:01 2020: Loading RX: RX_Port5
Fri Jun 12 03:20:01 2020: Loading TX: TX_Port5
Fri Jun 12 03:20:01 2020: ORP_HalfDuplexLogic_Port5: Event handler script successfully loaded.
Fri Jun 12 03:20:01 2020:
Fri Jun 12 03:20:01 2020: Starting logic: ORP_HalfDuplexLogic_Port6
Fri Jun 12 03:20:01 2020: Loading RX: RX_Port6
Fri Jun 12 03:20:01 2020: Loading TX: TX_Port6
Fri Jun 12 03:20:01 2020: ORP_HalfDuplexLogic_Port6: Event handler script successfully loaded.
Fri Jun 12 03:20:01 2020:
Fri Jun 12 03:20:01 2020: Starting logic: ORP_HalfDuplexLogic_Port7
Fri Jun 12 03:20:01 2020: Loading RX: RX_Port7
Fri Jun 12 03:20:01 2020: Loading TX: TX_Port7
Fri Jun 12 03:20:01 2020: ORP_HalfDuplexLogic_Port7: Event handler script successfully loaded.
Fri Jun 12 03:20:01 2020:
Fri Jun 12 03:20:01 2020: Starting logic: ORP_HalfDuplexLogic_Port8
Fri Jun 12 03:20:01 2020: Loading RX: RX_Port8
Fri Jun 12 03:20:01 2020: Loading TX: TX_Port8
Fri Jun 12 03:20:01 2020: ORP_HalfDuplexLogic_Port8: Event handler script successfully loaded.
Fri Jun 12 03:20:01 2020: Activating link LinkGroup1
Fri Jun 12 03:20:07 2020: RX_Port1: The squelch is OPEN (6.06462)
Fri Jun 12 03:20:07 2020: TX_Port1: Turning the transmitter ON
Fri Jun 12 03:20:07 2020: TX_Port2: Turning the transmitter ON
Fri Jun 12 03:20:07 2020: TX_Port3: Turning the transmitter ON
Fri Jun 12 03:20:07 2020: TX_Port4: Turning the transmitter ON
Fri Jun 12 03:20:07 2020: TX_Port5: Turning the transmitter ON
Fri Jun 12 03:20:07 2020: TX_Port6: Turning the transmitter ON
Fri Jun 12 03:20:07 2020: TX_Port7: Turning the transmitter ON
**Fri Jun 12 03:20:07 2020: TX_Port8: Turning the transmitter ON
Fri Jun 12 03:20:08 2020: SvxLink v1.7.0 Copyright (C) 2003-2019 Tobias Blomberg / SM0SVX**
Fri Jun 12 03:20:08 2020:
Fri Jun 12 03:20:08 2020: SvxLink comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
>

### With the config variable it behaves normally
>Fri Jun 12 03:23:21 2020: SvxLink v1.7.0 Copyright (C) 2003-2019 Tobias Blomberg / SM0SVX
Fri Jun 12 03:23:21 2020:
Fri Jun 12 03:23:21 2020: SvxLink comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
Fri Jun 12 03:23:21 2020: welcome to redistribute it in accordance with the terms and conditions in the
Fri Jun 12 03:23:21 2020: GNU GPL (General Public License) version 2 or later.
Fri Jun 12 03:23:21 2020:
Fri Jun 12 03:23:21 2020: Using configuration file: /etc/svxlink/svxlink.conf
Fri Jun 12 03:23:21 2020: --- Using sample rate 48000Hz
Fri Jun 12 03:23:21 2020:
Fri Jun 12 03:23:21 2020: Starting logic: ORP_FullDuplexLogic_Port1
Fri Jun 12 03:23:21 2020: Loading RX: RX_Port1
Fri Jun 12 03:23:21 2020: Loading TX: TX_Port1
Fri Jun 12 03:23:21 2020: ORP_FullDuplexLogic_Port1: Event handler script successfully loaded.
Fri Jun 12 03:23:21 2020:
Fri Jun 12 03:23:21 2020: Starting logic: ORP_HalfDuplexLogic_Port2
Fri Jun 12 03:23:21 2020: Loading RX: RX_Port2
Fri Jun 12 03:23:21 2020: Loading TX: TX_Port2
Fri Jun 12 03:23:21 2020: ORP_HalfDuplexLogic_Port2: Event handler script successfully loaded.
Fri Jun 12 03:23:21 2020:
Fri Jun 12 03:23:21 2020: Starting logic: ORP_HalfDuplexLogic_Port3
Fri Jun 12 03:23:21 2020: Loading RX: RX_Port3
Fri Jun 12 03:23:21 2020: Loading TX: TX_Port3
Fri Jun 12 03:23:21 2020: ORP_HalfDuplexLogic_Port3: Event handler script successfully loaded.
Fri Jun 12 03:23:21 2020:
Fri Jun 12 03:23:21 2020: Starting logic: ORP_HalfDuplexLogic_Port4
Fri Jun 12 03:23:21 2020: Loading RX: RX_Port4
Fri Jun 12 03:23:21 2020: Loading TX: TX_Port4
Fri Jun 12 03:23:21 2020: ORP_HalfDuplexLogic_Port4: Event handler script successfully loaded.
Fri Jun 12 03:23:21 2020:
Fri Jun 12 03:23:21 2020: Starting logic: ORP_HalfDuplexLogic_Port5
Fri Jun 12 03:23:21 2020: Loading RX: RX_Port5
Fri Jun 12 03:23:21 2020: Loading TX: TX_Port5
Fri Jun 12 03:23:21 2020: ORP_HalfDuplexLogic_Port5: Event handler script successfully loaded.
Fri Jun 12 03:23:21 2020:
Fri Jun 12 03:23:21 2020: Starting logic: ORP_HalfDuplexLogic_Port6
Fri Jun 12 03:23:21 2020: Loading RX: RX_Port6
Fri Jun 12 03:23:21 2020: Loading TX: TX_Port6
Fri Jun 12 03:23:21 2020: ORP_HalfDuplexLogic_Port6: Event handler script successfully loaded.
Fri Jun 12 03:23:21 2020:
Fri Jun 12 03:23:21 2020: Starting logic: ORP_HalfDuplexLogic_Port7
Fri Jun 12 03:23:21 2020: Loading RX: RX_Port7
Fri Jun 12 03:23:21 2020: Loading TX: TX_Port7
Fri Jun 12 03:23:21 2020: ORP_HalfDuplexLogic_Port7: Event handler script successfully loaded.
Fri Jun 12 03:23:21 2020:
Fri Jun 12 03:23:21 2020: Starting logic: ORP_HalfDuplexLogic_Port8
Fri Jun 12 03:23:21 2020: Loading RX: RX_Port8
Fri Jun 12 03:23:21 2020: Loading TX: TX_Port8
Fri Jun 12 03:23:21 2020: ORP_HalfDuplexLogic_Port8: Event handler script successfully loaded.
Fri Jun 12 03:23:21 2020: Activating link LinkGroup1
Fri Jun 12 03:23:27 2020: RX_Port1: The squelch is OPEN (3.61302)
Fri Jun 12 03:23:27 2020: TX_Port1: Turning the transmitter ON
Fri Jun 12 03:23:27 2020: TX_Port2: Turning the transmitter ON
Fri Jun 12 03:23:27 2020: TX_Port3: Turning the transmitter ON
Fri Jun 12 03:23:27 2020: TX_Port4: Turning the transmitter ON
Fri Jun 12 03:23:27 2020: TX_Port5: Turning the transmitter ON
Fri Jun 12 03:23:27 2020: TX_Port6: Turning the transmitter ON
Fri Jun 12 03:23:27 2020: TX_Port7: Turning the transmitter ON
Fri Jun 12 03:23:27 2020: TX_Port8: Turning the transmitter ON
Fri Jun 12 03:23:29 2020: ORP_FullDuplexLogic_Port1: digit=*
Fri Jun 12 03:23:30 2020: TX_Port2: Turning the transmitter OFF
Fri Jun 12 03:23:30 2020: TX_Port3: Turning the transmitter OFF
Fri Jun 12 03:23:30 2020: TX_Port4: Turning the transmitter OFF
Fri Jun 12 03:23:30 2020: TX_Port5: Turning the transmitter OFF
Fri Jun 12 03:23:30 2020: TX_Port6: Turning the transmitter OFF
Fri Jun 12 03:23:30 2020: TX_Port7: Turning the transmitter OFF
Fri Jun 12 03:23:30 2020: RX_Port1: The squelch is CLOSED (-0.119985)
Fri Jun 12 03:23:30 2020: TX_Port8: Turning the transmitter OFF
Fri Jun 12 03:23:44 2020: TX_Port1: Turning the transmitter OFF

### Here is the config file (with the variable included)

[GLOBAL]
MODULE_PATH=/usr/lib/arm-linux-gnueabihf/svxlink
LOGICS=ORP_FullDuplexLogic_Port1,ORP_HalfDuplexLogic_Port2,ORP_HalfDuplexLogic_Port3,ORP_HalfDuplexLogic_Port4,ORP_HalfDuplexLogic_Port5,ORP_HalfDuplexLogic_Port6,ORP_HalfDuplexLogic_Port7,ORP_HalfDuplexLogic_Port8
CFG_DIR=svxlink.d
TIMESTAMP_FORMAT="%c"
CARD_SAMPLE_RATE=48000
LINKS=LinkGroup1
CARD_CHANNELS=8
###############################################################################

[RX_Port1]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=1
SQL_DET=GPIO
GPIO_SQL_PIN=gpio462
SQL_HANGTIME=10
SQL_START_DELAY=1
SQL_DELAY=10
SIGLEV_SLOPE=1
SIGLEV_OFFSET=0
SIGLEV_OPEN_THRESH=30
SIGLEV_CLOSE_THRESH=10
DEEMPHASIS=1
PEAK_METER=0
DTMF_DEC_TYPE=INTERNAL
DTMF_MUTING=1
DTMF_HANGTIME=100
DTMF_SERIAL=/dev/ttyS0

###############################################################################

[TX_Port1]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=0
PTT_HANGTIME=2000
TIMEOUT=300
TX_DELAY=50
PTT_TYPE=GPIO
PTT_PORT=GPIO
PTT_PIN=gpio458
PREEMPHASIS=0
DTMF_TONE_LENGTH=100
DTMF_TONE_SPACING=50
DTMF_TONE_PWR=-18

###############################################################################

[ORP_FullDuplexLogic_Port1]
TYPE=Repeater
RX=RX_Port1
TX=TX_Port1
#MODULES=NONE
CALLSIGN=KG7PAR
SHORT_IDENT_INTERVAL=10
LONG_IDENT_INTERVAL=60
EVENT_HANDLER=/usr/share/svxlink/events.tcl
DEFAULT_LANG=en_US
RGR_SOUND_DELAY=1
TX_CTCSS=ALWAYS
FX_GAIN_NORMAL=0
FX_GAIN_LOW=-12
IDLE_TIMEOUT=1
OPEN_ON_SQL=1
OPEN_SQL_FLANK=OPEN
IDLE_SOUND_INTERVAL=0

###############################################################################

[RX_Port2]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=0
SQL_DET=GPIO
GPIO_SQL_PIN=gpio463
SQL_HANGTIME=10
SQL_START_DELAY=1
SQL_DELAY=10
SIGLEV_SLOPE=1
SIGLEV_OFFSET=0
SIGLEV_OPEN_THRESH=30
SIGLEV_CLOSE_THRESH=10
DEEMPHASIS=1
PEAK_METER=0
DTMF_DEC_TYPE=INTERNAL
DTMF_MUTING=1
DTMF_HANGTIME=100
DTMF_SERIAL=/dev/ttyS0

###############################################################################

[TX_Port2]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=1
PTT_HANGTIME=2000
TIMEOUT=300
TX_DELAY=50
PTT_TYPE=GPIO
PTT_PORT=GPIO
PTT_PIN=gpio459
PREEMPHASIS=0
DTMF_TONE_LENGTH=100
DTMF_TONE_SPACING=50
DTMF_TONE_PWR=-18

###############################################################################

[ORP_HalfDuplexLogic_Port2]
TYPE=Simplex
RX=RX_Port2
TX=TX_Port2
CALLSIGN=KG7PAR
SHORT_IDENT_INTERVAL=10
LONG_IDENT_INTERVAL=60
EVENT_HANDLER=/usr/share/svxlink/events.tcl
DEFAULT_LANG=en_US
RGR_SOUND_DELAY=1
TX_CTCSS=ALWAYS
FX_GAIN_NORMAL=0
FX_GAIN_LOW=-12
IDLE_TIMEOUT=1
OPEN_ON_SQL=1
OPEN_SQL_FLANK=OPEN
IDLE_SOUND_INTERVAL=0

###############################################################################

[RX_Port3]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=3
SQL_DET=GPIO
GPIO_SQL_PIN=gpio470
SQL_HANGTIME=10
SQL_START_DELAY=1
SQL_DELAY=10
SIGLEV_SLOPE=1
SIGLEV_OFFSET=0
SIGLEV_OPEN_THRESH=30
SIGLEV_CLOSE_THRESH=10
DEEMPHASIS=1
PEAK_METER=0
DTMF_DEC_TYPE=INTERNAL
DTMF_MUTING=1
DTMF_HANGTIME=100
DTMF_SERIAL=/dev/ttyS0

###############################################################################

[TX_Port3]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=3
PTT_HANGTIME=2000
TIMEOUT=300
TX_DELAY=50
PTT_TYPE=GPIO
PTT_PORT=GPIO
PTT_PIN=gpio466
PREEMPHASIS=0
DTMF_TONE_LENGTH=100
DTMF_TONE_SPACING=50
DTMF_TONE_PWR=-18

###############################################################################

[ORP_HalfDuplexLogic_Port3]
TYPE=Simplex
RX=RX_Port3
TX=TX_Port3
CALLSIGN=KG7PAR
SHORT_IDENT_INTERVAL=10
LONG_IDENT_INTERVAL=60
EVENT_HANDLER=/usr/share/svxlink/events.tcl
DEFAULT_LANG=en_US
RGR_SOUND_DELAY=1
TX_CTCSS=ALWAYS
FX_GAIN_NORMAL=0
FX_GAIN_LOW=-12
IDLE_TIMEOUT=1
OPEN_ON_SQL=1
OPEN_SQL_FLANK=OPEN
IDLE_SOUND_INTERVAL=0

###############################################################################

[RX_Port4]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=2
SQL_DET=GPIO
GPIO_SQL_PIN=gpio471
SQL_HANGTIME=10
SQL_START_DELAY=1
SQL_DELAY=10
SIGLEV_SLOPE=1
SIGLEV_OFFSET=0
SIGLEV_OPEN_THRESH=30
SIGLEV_CLOSE_THRESH=10
DEEMPHASIS=1
PEAK_METER=0
DTMF_DEC_TYPE=INTERNAL
DTMF_MUTING=1
DTMF_HANGTIME=100
DTMF_SERIAL=/dev/ttyS0

###############################################################################

[TX_Port4]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=2
PTT_HANGTIME=2000
TIMEOUT=300
TX_DELAY=50
PTT_TYPE=GPIO
PTT_PORT=GPIO
PTT_PIN=gpio467
PREEMPHASIS=0
DTMF_TONE_LENGTH=100
DTMF_TONE_SPACING=50
DTMF_TONE_PWR=-18

###############################################################################

[ORP_HalfDuplexLogic_Port4]
TYPE=Simplex
RX=RX_Port4
TX=TX_Port4
CALLSIGN=KG7PAR
SHORT_IDENT_INTERVAL=10
LONG_IDENT_INTERVAL=60
EVENT_HANDLER=/usr/share/svxlink/events.tcl
DEFAULT_LANG=en_US
RGR_SOUND_DELAY=1
TX_CTCSS=ALWAYS
FX_GAIN_NORMAL=0
FX_GAIN_LOW=-12
IDLE_TIMEOUT=1
OPEN_ON_SQL=1
OPEN_SQL_FLANK=OPEN
IDLE_SOUND_INTERVAL=0

###############################################################################

[RX_Port5]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=5
SQL_DET=GPIO
GPIO_SQL_PIN=gpio478
SQL_HANGTIME=10
SQL_START_DELAY=1
SQL_DELAY=10
SIGLEV_SLOPE=1
SIGLEV_OFFSET=0
SIGLEV_OPEN_THRESH=30
SIGLEV_CLOSE_THRESH=10
DEEMPHASIS=1
PEAK_METER=0
DTMF_DEC_TYPE=INTERNAL
DTMF_MUTING=1
DTMF_HANGTIME=100
DTMF_SERIAL=/dev/ttyS0

###############################################################################

[TX_Port5]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=5
PTT_HANGTIME=2000
TIMEOUT=300
TX_DELAY=50
PTT_TYPE=GPIO
PTT_PORT=GPIO
PTT_PIN=gpio474
PREEMPHASIS=0
DTMF_TONE_LENGTH=100
DTMF_TONE_SPACING=50
DTMF_TONE_PWR=-18

###############################################################################

[ORP_HalfDuplexLogic_Port5]
TYPE=Simplex
RX=RX_Port5
TX=TX_Port5
CALLSIGN=KG7PAR
SHORT_IDENT_INTERVAL=10
LONG_IDENT_INTERVAL=60
EVENT_HANDLER=/usr/share/svxlink/events.tcl
DEFAULT_LANG=en_US
RGR_SOUND_DELAY=1
TX_CTCSS=ALWAYS
FX_GAIN_NORMAL=0
FX_GAIN_LOW=-12
IDLE_TIMEOUT=1
OPEN_ON_SQL=1
OPEN_SQL_FLANK=OPEN
IDLE_SOUND_INTERVAL=0

###############################################################################

[RX_Port6]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=4
SQL_DET=GPIO
GPIO_SQL_PIN=gpio479
SQL_HANGTIME=10
SQL_START_DELAY=1
SQL_DELAY=10
SIGLEV_SLOPE=1
SIGLEV_OFFSET=0
SIGLEV_OPEN_THRESH=30
SIGLEV_CLOSE_THRESH=10
DEEMPHASIS=1
PEAK_METER=0
DTMF_DEC_TYPE=INTERNAL
DTMF_MUTING=1
DTMF_HANGTIME=100
DTMF_SERIAL=/dev/ttyS0

###############################################################################

[TX_Port6]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=4
PTT_HANGTIME=2000
TIMEOUT=300
TX_DELAY=50
PTT_TYPE=GPIO
PTT_PORT=GPIO
PTT_PIN=gpio475
PREEMPHASIS=0
DTMF_TONE_LENGTH=100
DTMF_TONE_SPACING=50
DTMF_TONE_PWR=-18

###############################################################################

[ORP_HalfDuplexLogic_Port6]
TYPE=Simplex
RX=RX_Port6
TX=TX_Port6
CALLSIGN=KG7PAR
SHORT_IDENT_INTERVAL=10
LONG_IDENT_INTERVAL=60
EVENT_HANDLER=/usr/share/svxlink/events.tcl
DEFAULT_LANG=en_US
RGR_SOUND_DELAY=1
TX_CTCSS=ALWAYS
FX_GAIN_NORMAL=0
FX_GAIN_LOW=-12
IDLE_TIMEOUT=1
OPEN_ON_SQL=1
OPEN_SQL_FLANK=OPEN
IDLE_SOUND_INTERVAL=0

###############################################################################

[RX_Port7]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=7
SQL_DET=GPIO
GPIO_SQL_PIN=gpio486
SQL_HANGTIME=10
SQL_START_DELAY=1
SQL_DELAY=10
SIGLEV_SLOPE=1
SIGLEV_OFFSET=0
SIGLEV_OPEN_THRESH=30
SIGLEV_CLOSE_THRESH=10
DEEMPHASIS=1
PEAK_METER=0
DTMF_DEC_TYPE=INTERNAL
DTMF_MUTING=1
DTMF_HANGTIME=100
DTMF_SERIAL=/dev/ttyS0

###############################################################################

[TX_Port7]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=7
PTT_HANGTIME=2000
TIMEOUT=300
TX_DELAY=50
PTT_TYPE=GPIO
PTT_PORT=GPIO
PTT_PIN=gpio482
PREEMPHASIS=0
DTMF_TONE_LENGTH=100
DTMF_TONE_SPACING=50
DTMF_TONE_PWR=-18

###############################################################################

[ORP_HalfDuplexLogic_Port7]
TYPE=Simplex
RX=RX_Port7
TX=TX_Port7
CALLSIGN=KG7PAR
SHORT_IDENT_INTERVAL=10
LONG_IDENT_INTERVAL=60
EVENT_HANDLER=/usr/share/svxlink/events.tcl
DEFAULT_LANG=en_US
RGR_SOUND_DELAY=1
TX_CTCSS=ALWAYS
FX_GAIN_NORMAL=0
FX_GAIN_LOW=-12
IDLE_TIMEOUT=1
OPEN_ON_SQL=1
OPEN_SQL_FLANK=OPEN
IDLE_SOUND_INTERVAL=0

###############################################################################

[RX_Port8]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=6
SQL_DET=GPIO
GPIO_SQL_PIN=gpio487
SQL_HANGTIME=10
SQL_START_DELAY=1
SQL_DELAY=10
SIGLEV_SLOPE=1
SIGLEV_OFFSET=0
SIGLEV_OPEN_THRESH=30
SIGLEV_CLOSE_THRESH=10
DEEMPHASIS=1
PEAK_METER=0
DTMF_DEC_TYPE=INTERNAL
DTMF_MUTING=1
DTMF_HANGTIME=100
DTMF_SERIAL=/dev/ttyS0

###############################################################################

[TX_Port8]
TYPE=Local
AUDIO_DEV=alsa:plughw:1
AUDIO_CHANNEL=6
PTT_HANGTIME=2000
TIMEOUT=300
TX_DELAY=50
PTT_TYPE=GPIO
PTT_PORT=GPIO
PTT_PIN=gpio483
PREEMPHASIS=0
DTMF_TONE_LENGTH=100
DTMF_TONE_SPACING=50
DTMF_TONE_PWR=-18

###############################################################################

[ORP_HalfDuplexLogic_Port8]
TYPE=Simplex
RX=RX_Port8
TX=TX_Port8
CALLSIGN=KG7PAR
SHORT_IDENT_INTERVAL=10
LONG_IDENT_INTERVAL=60
EVENT_HANDLER=/usr/share/svxlink/events.tcl
DEFAULT_LANG=en_US
RGR_SOUND_DELAY=1
TX_CTCSS=ALWAYS
FX_GAIN_NORMAL=0
FX_GAIN_LOW=-12
IDLE_TIMEOUT=1
OPEN_ON_SQL=1
OPEN_SQL_FLANK=OPEN
IDLE_SOUND_INTERVAL=0

###############################################################################

[LinkGroup1]
CONNECT_LOGICS=ORP_FullDuplexLogic_Port1:81:KG7PAR,ORP_HalfDuplexLogic_Port2:81:KG7PAR,ORP_HalfDuplexLogic_Port3:81:KG7PAR,ORP_HalfDuplexLogic_Port4:81:KG7PAR,ORP_HalfDuplexLogic_Port5:81:KG7PAR,ORP_HalfDuplexLogic_Port6:81:KG7PAR,ORP_HalfDuplexLogic_Port7:81:KG7PAR,ORP_HalfDuplexLogic_Port8:81:KG7PAR
DEFAULT_ACTIVE=1

**Comment by sm0svx** [comment]
Fixed in commit b38dff32ecb0f4e4b193a65d5ee0a891dbbe1cbb
