### ISSUE TITLE
Qtel QT Libraries

### ISSUE THREAD

**Issue by kb6ibb** [sm0svx/svxlink#512]
Qtel requires QT4, which is now obsolete and no longer included at the Enterprise level and forward rolling releases.  Requires update to QT 5.2 for build.

**Comment by sm0svx** [comment]
It builds fine with Qt 5. The port to Qt 5 was made in like 2015. What version of the code are you using to build and why is it that you end up saying that it need Qt 4?

I'll close this issue for now but feel free to reopen it if you still think that Qtel require Qt 4 somewhere.
