### ISSUE TITLE
Multi Stage build

### ISSUE THREAD

**Issue by joergklein** [sm0svx/svxlink#516]
The Docker image, which I build works fine. I would like to have some more feature.
1. Multi Stage Build
2. Save all config files outside the docker container.

Here are the links to the Docker and GitHub Repo:
https://hub.docker.com/r/joergklein/svxlink
https://github.com/joergklein/docker-svxlink

Thank you for the help

**Comment by sm0svx** [comment]
That docker build is not part of the SvxLink project. Please try to contact the maintainer of that Docker image, maybe by writing an issue in that projects issue tracker on GitHub.
