### ISSUE TITLE
Dump: LinkManager* LinkManager::instance(): Assertion `_instance != 0' failed

### ISSUE THREAD

**Issue by dl7ata** [sm0svx/svxlink#529]
It seems to be the same issue as [https://groups.io/g/svxlink/topic/45399694?p=Created,,,20,2,0,0::recentpostdate%2Fsticky,,,20,1,40,45399694](url) running on a 486 machine with current Linux mint:

svxlink@weewx-reserve:~$ svxlink
SvxLink v1.7.99.36 Copyright (C) 2003-2020 Tobias Blomberg / SM0SVX

SvxLink comes with ABSOLUTELY NO WARRANTY. This is free software, and you
are
welcome to redistribute it in accordance with the terms and conditions in
the
GNU GPL (General Public License) version 2 or later.

Using configuration file: /etc/svxlink/svxlink.conf
--- Using sample rate 48000Hz

Starting logic: SimplexLogic
Loading RX: Rx1
Loading TX: Tx1
Loading module "ModuleHelp" into logic "SimplexLogic"
        Found /usr/lib/i386-linux-gnu/svxlink/ModuleHelp.so
        Module Help v1.0.0 starting...
Loading module "ModuleParrot" into logic "SimplexLogic"
        Found /usr/lib/i386-linux-gnu/svxlink/ModuleParrot.so
        Module Parrot v1.1.1 starting...
Loading module "ModuleEchoLink" into logic "SimplexLogic"
        Found /usr/lib/i386-linux-gnu/svxlink/ModuleEchoLink.so
        Module EchoLink v1.5.99.0 starting...
Loading module "ModuleMetarInfo" into logic "SimplexLogic"
        Found /usr/lib/i386-linux-gnu/svxlink/ModuleMetarInfo.so
        Module MetarInfo v1.2.1.99.2 starting...
SimplexLogic: Event handler script successfully loaded.
EchoLink directory status changed to ON
--- EchoLink directory server message: ---
EchoLink Server v2.5.9997

ECHO4: Frankfurt, Germany

SimplexLogic: digit=0
SimplexLogic: digit=#
SimplexLogic: Activating module Help...
svxlink: /home/dh3pae/svxlink/src/svxlink/svxlink/LinkManager.h:179: static
LinkManager* LinkManager::instance(): Assertion `_instance != 0' failed.
Abgebrochen (Speicherabzug geschrieben)
svxlink@weewx-reserve:~$

**Comment by sm0svx** [comment]
Should now be fixed in latest master
