### ISSUE TITLE
CMake: OGG not found

### ISSUE THREAD

**Issue by ur3qjw** [sm0svx/svxlink#534]
Hello Tobias!

For a long time, I've noticed this message:
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found Opus: /usr/lib/i386-linux-gnu/libopus.so (found version "1.1.2") 
-- Could NOT find OGG (missing: OGG_LIBRARY OGG_INCLUDE_DIR)
vorbis-tools v.1.4.0-10.1, package - installed.
But apparently pkg-config cannot find it.

But, after installing the libvorbis-dev v.1.3.5-4.2 package, he found library:
-- Found OGG: /usr/lib/i386-linux-gnu/libogg.so (found version "1.3.2") 

Regards, Volodymyr

**Comment by sm0svx** [comment]
Ogg is not used for anything in SvxLink right now so you actually don't need it. But if you want to quiet the warning you should install libogg-dev. The reason it worked for you is because libvorbis-dev pulls in libogg-dev as a dependency.
