### ISSUE TITLE
I have been Using Echolink win Windows

### ISSUE THREAD

**Issue by cnavarro76** [sm0svx/svxlink#542]
I Have been using echolink with win10 on my desktop computer, I have the echolink connected to my radio a Yaesu FT-991 with an USB cable. RX with VOX and TX COM 3 PTT RTS. and it works great. 

Im trying to set up a SVX echolink node with SVX link on a raspberry Pi. I got so far as installing SVX link, and configuring svxlink.conf and ModuleEchoLink.conf. (I can see the node on my phone app).  I get an audio annoucement you have connected to a svxlink node...
However when I TX from my radio, I do not hear anything on the echolink app on my phone, nor the other way around.

I have also set the correct ALSA card both on the ALSA.conf and on the SVXlink.conf (Card 2 USB Audio CODEC)

My guess is that im missing the ptt configuration. but do not know how to do this.

Any help would be greatly appreciated
XE1CNA

**Comment by sm0svx** [comment]
Hi! This is not a support forum. If you need help getting started with SvxLink you should use the [groups.io](https://groups.io/g/svxlink/) discussion forum.
