### ISSUE TITLE
Is their a way to Password or Lock down the EchoLink modules DTMF Control codes??

### ISSUE THREAD

**Issue by k9oy** [sm0svx/svxlink#544]
Hello:

Have SvxLink running on a Raspberry Pi 4.  V1.6.1 with EchoLink server v2.6.103.
We have some malicious interference in our area, they keep sending the EchoLink kill code "##" disconnecting all connected stations in the midst of conversation.

Can you please explain to me if their is a way to password the common DTMF control codes #, ##, 0#, 1#, 2#, 31#, 32#,  4#, 50# 51#....??   

Or is their a way to disable all DTMF control on SvxLink, and maybe instead have a MASTER listening DTMF code command, that will then enable the regular DTMF controlling for lets say ~30 seconds, giving enough time to control the SvxLink, before  defaulting back to a non-controlling DTMF state??  Could also have the DTMF control time reset and stay active, for longer then the 30 second windows time limit as long as their is active DTMF codes being sent. 
 
Or if this is the easier way to do it, can you explain where these common DTMF codes are stored; and if they can be changed within the SvxLink servers programming files/scripts.  Been looking for a week, and not having any luck finding the file where they are stored at on the SvxLink server.

Thanks;
Gregory (K9OY)...

**Comment by sm0svx** [comment]
Hi Gregory! This is not a support forum. You should try asking questions at [groups.io](https://groups.io/g/svxlink/) instead. You can do some customizations using TCL scripting but I'm sure someone can help you with that at groups.io.
