### ISSUE TITLE
Ignoring incoming connection

### ISSUE THREAD

**Issue by dbahiense** [sm0svx/svxlink#550]
I live in a condominium that provides the Internet for each house through NAT.
Outside the condominium I'm able to set svxlink-server without problems and clients can also connect via qtel or app.
But inside the condominium I manage to connect to the Echolink servers, but when someone tries to connect to my svxlink they receive a Time Out Error and in the server I can read:

Spourious audio packet received from 192.168.2.169 (**that's my gateway**)
Incoming Echolink connection from PY1II (Douglas,) at 192.168.2.169
*** WARNING: Ignoring incoming connection from PY1II since the IP address registered in the directory server (44.190.12.84) is not the same as the remote IP address (192.168.2.169) of the incoming connection.

We've already set the ports in my router, in condominium's router, let all open, we tried everything, but always with the same bad result.

The closest issue we read here: https://github.com/sm0svx/svxlink/issues/93 that mentions this WARNING. But was little help.

What do we need to change in the config to solve this topology problem?

**Comment by sm0svx** [comment]
This is not a bug. You'd probably get an answer more quickly if using the discussion forum at [groups.io](https://groups.io/g/svxlink/).

Your gateway is doing source NAT (192.168.2.169) which will hide the real IP address (44.190.12.84). As a security measure, SvxLink will refuse to accept UDP packets (audio+link control) if the source IP address does not match the one registered in the Echolink registry server. You must ensure that your network setup preserve the real source address. If that is not possible you need to use an Echolink proxy server. There are publicly available proxy server. Ask at groups.io if you are unsure.
