### ISSUE TITLE
ModuleEchoLink. Incorrect message from the directory server.

### ISSUE THREAD

**Issue by ur3qjw** [sm0svx/svxlink#595]
Hello Tobias!
I noticed that I began to receive incorrect messages from the directory server.
If the EchoLink password is incorrect, the server, returns the Ok status anyway.
Tested on SvxLink v.1.7.99.67, 1.7.99.72.

Log output. The password is initially incorrect.
30.08.2022 20:01:07: EchoLink directory status changed to ON
30.08.2022 20:01:08: --- EchoLink directory server message: ---
30.08.2022 20:01:08: EchoLink Server v2.6.104
30.08.2022 20:01:08: 
30.08.2022 20:01:08: ECHO6: N.Virginia, USA

**Comment by sm0svx** [comment]
Sounds more like a bug in the Echolink directory server then if it lets you in even though you are giving it the incorrect password, doesn't it?

**Comment by ur3qjw** [comment]
If the password is incorrect, the station is not in the station list.
Windows client v.2.0.908, also writes: "Incorrect password".

![Incorrect_pass](https://user-images.githubusercontent.com/16563084/187553860-d098201f-9222-4659-89a7-206404ba8f78.png)
