### ISSUE TITLE
command should trigger `printSquelchState`

### ISSUE THREAD

**Issue by hsmade** [sm0svx/svxlink#609]
Since the `printSquelchState` shows the state of RXes, `printSquelchState` should be called when a command is handled (to enable or disable an RX).
Currently, it's impossible to see if any RXes are enabled/disabled, unless there is traffic to trigger the `printSquelchState`.

**Comment by sm0svx** [comment]
Fixed by commit bd629e3c5829899c39c6540ff4914c35a72a64aa
