### ISSUE TITLE
VOTER and MUTE receiver don't send JSON state

### ISSUE THREAD

**Issue by sp2ong** [sm0svx/svxlink#624]
Hi,

When I set the receiver to MUTE mode via COMMAND_PTY in VOTER in svxlink log there is info

2023-04-20 18:17:29: Voter[Rx1]: The squelch is OPEN (siglev=58) [MUTED].
2023-04-20 18:17:31: Voter[Rx1]: The squelch is CLOSED (siglev=35) [MUTED].

But monitoring 
cat /tmp/svx_stat with STATE_PTY defined in [SimplexLogic].
there is no information , when I set the receiver to ENABLED mode via COMMAND_PTY Voter there is information about the receiver

1682007367.949 Voter:sql_state [{"active":true,"enabled":true,"id":"R","name":"Rx1","siglev":58,"sql_open":true}]
1682007368.607 Voter:sql_state [{"active":false,"enabled":true,"id":"R","name":"Rx1","siglev":72,"sql_open":false}]

I see that there is an option in the status "enabled": true so it looks like when the receiver is in MUTE mode it seems that there should be information on STATE_PTY with receiver information "enabled": false but it is not displayed

**Comment by sm0svx** [comment]
Fixed in latest master with commit bd629e3c5829899c39c6540ff4914c35a72a64aa
