### ISSUE TITLE
CTCSS_DEBUG

### ISSUE THREAD

**Issue by OE9SAU** [sm0svx/svxlink#687]
Hello together
i want to use the CTCSS_DEBUG. I putted CTCSS_DEBUG=1 into the RX config section.
But i cant see any CTCSS Debug informations inside the log.
What doing im wrong or is there any other config setting missing?
Thanks for any hint.
73 de Martin, OE9SAU

**Comment by sm0svx** [comment]
Please use the [groups.io](https://groups.io/g/svxlink/) forum for asking questions. Re-post your question there if this is still a problem.
