### ISSUE TITLE
Hang during exit

### ISSUE THREAD

**Issue by pe1chl** [sm0svx/svxlink#95]
Sometimes when we use "service svxlink restart" the svxlink program is running twice after the restart.
I found that the init script (Debian version) sends it a TERM signal, which is detected OK and the program
starts to shutdown, but apparently it does not completely exit.   It causes no trouble for the next instance
that is started after that, but it remains in the process list and it is detected by our nagios monitoring that
checks if one and only one instance of svxlink is running on the system.

When this occurs, I see that the old instance has a child process which is a "sh", and is in Z (zombie) state.
Probably the result of running an external program, and not correctly waiting for the child.
Maybe it is related to the QSO recorder being running the ENCODER_CMD at that time?

I have not yet checked what the program is doing when this occurs, only what the process structure
was.  When it happens again I will do an strace.

**Comment by sm0svx** [comment]
Is this still an issue?  Have you investigated it further?  It would be nice to know exactly in which read it get stuck. Can you run it under gdb to get a stack trace?

**Comment by pe1chl** [comment]
It has not happened for some time.   It appears to have gone away.  I did quite some restarting today (running the latest git master) and it has not happened.

**Comment by sm0svx** [comment]
OK, good. Maybe this was an effect of a bug that I fixed on Fri Jan 9 09:48:57 2015 +0100 in commit 2de0a4887716d9c82163c1a4d26f42b28dcf7671. Or something else...

I'll close this issue for now. Reopen it if the problem reappears.

**Comment by pe1chl** [comment]
It could also have been cause by build errors on our systems.  It appears that switching from the old make to cmake without cleaning the directory causes some issues.  I noticed it when the version number of the built program was still old after an update.  Removed the entire directory and did a new git clone a week or two ago.  Also removed all old traces before re-installing it.
